import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { getClientErrorLogs,getContentQualitySummary,getContentReviewQueue,getFeedbackQueue,setContentReviewStatus,setFeedbackStatus,type ClientErrorItem,type FeedbackItem,type FeedbackStatus,type QualitySummary,type ReviewQuestion,type ReviewQueue } from '../services/adminApi'
import './AdminPage.css'

const kindLabel={bug:'Bug',content:'Contenu',suggestion:'Suggestion'} as const
const statusLabel:Record<FeedbackStatus,string>={new:'Nouveau',reviewed:'Revu',resolved:'Résolu'}
const typeLabel:Record<string,string>={mcq:'QCM',true_false:'Vrai/Faux',fill_blank:'Texte à trou',matching:'Association',hotspot:'Repérage',image:'Étiquetage',short_answer:'Réponse courte',translation:'Traduction',clinical_case:'Cas clinique'}

function reviewReadiness(item:ReviewQuestion){
 if(!item.source_title||!item.source_page||!item.source_excerpt)return{ready:false,reason:'Source incomplète'}
 if(item.type==='mcq'&&(item.option_count<2||item.correct_option_count<1))return{ready:false,reason:'Options manquantes'}
 if(item.type==='true_false'&&(item.option_count!==2||item.correct_option_count!==1))return{ready:false,reason:'Vrai/Faux incomplet'}
 if((item.type==='hotspot'||item.type==='image')&&!item.visual_approved)return{ready:false,reason:'Visuel à contrôler'}
 if(item.quality_issue)return{ready:false,reason:item.quality_issue==='missing_answer_options'?'Options manquantes':'Qualité à revoir'}
 return{ready:true,reason:'Prête'}
}

export default function AdminPage(){
 const [summary,setSummary]=useState<QualitySummary|null>(null)
 const [items,setItems]=useState<FeedbackItem[]>([])
 const [clientErrors,setClientErrors]=useState<ClientErrorItem[]>([])
 const [review,setReview]=useState<ReviewQueue|null>(null)
 const [filter,setFilter]=useState<FeedbackStatus|null>('new')
 const [reviewFilter,setReviewFilter]=useState<'all'|'review'|'validated'|'blocked'>('all')
 const [busyId,setBusyId]=useState<string|null>(null)
 const [error,setError]=useState<string|null>(null)
 async function load(status=filter){setError(null);try{const [s,f,r,c]=await Promise.all([getContentQualitySummary(),getFeedbackQueue(status,100),getContentReviewQueue(),getClientErrorLogs(50)]);setSummary(s);setItems(f);setReview(r);setClientErrors(c)}catch(e){setError(e instanceof Error?e.message:'Impossible de charger l’administration.')}}
 useEffect(()=>{void load()},[])
 async function changeStatus(id:string,status:FeedbackStatus){setBusyId(id);try{await setFeedbackStatus(id,status);await load(filter)}catch(e){setError(e instanceof Error?e.message:'Impossible de mettre à jour ce retour.')}finally{setBusyId(null)}}
 async function changeFilter(status:FeedbackStatus|null){setFilter(status);setError(null);try{setItems(await getFeedbackQueue(status,100))}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les retours.')}}
 async function changeContentStatus(item:ReviewQuestion,status:'review'|'validated'|'published'){setBusyId(item.id);setError(null);try{await setContentReviewStatus(item.id,status);await load(filter)}catch(e){setError(e instanceof Error?e.message:'Impossible de modifier ce contenu.')}finally{setBusyId(null)}}
 const reviewItems=useMemo(()=>{if(!review)return[];return review.questions.filter(item=>{const readiness=reviewReadiness(item);if(reviewFilter==='review')return item.validation_status==='review';if(reviewFilter==='validated')return item.validation_status==='validated';if(reviewFilter==='blocked')return !readiness.ready;return true})},[review,reviewFilter])
 if(error&&!summary)return <section className="card"><p className="eyebrow">Administration</p><h1>Accès indisponible</h1><p>{error}</p></section>
 if(!summary||!review)return <section className="card"><p>Chargement du centre de contrôle…</p></section>
 return <div className="stack admin-stack">
  <section className="hero-card"><div className="hero-copy"><span className="hero-kicker">Administration</span><h1>Qualité & retours Kineo</h1><p>Contrôle la traçabilité pédagogique, valide les questions et traite les anomalies remontées pendant les tests.</p></div><div className="hero-orbit"><span>✓</span></div></section>
  <section className="admin-metrics"><article className="metric-card"><span className="metric-icon">📚</span><div><small>Questions publiées</small><strong>{summary.quality.published_total}</strong></div></article><article className="metric-card"><span className="metric-icon">📄</span><div><small>CM validés</small><strong>{summary.documents.validated}/{summary.documents.total}</strong></div></article><article className="metric-card"><span className="metric-icon">⚠</span><div><small>Visuels en quarantaine</small><strong>{summary.quality.visual_quarantined}</strong></div></article><article className="metric-card"><span className="metric-icon">💬</span><div><small>Nouveaux retours</small><strong>{summary.feedback.new_feedback}</strong></div></article></section>
  {summary.quality.visual_quarantined>0&&<section className="card challenge-card"><div className="challenge-icon">🦴</div><div className="challenge-copy"><p className="eyebrow">Validation anatomique</p><h2>{summary.quality.visual_quarantined} visuel{summary.quality.visual_quarantined>1?'s':''} à contrôler</h2><p>Ouvre la file dédiée pour vérifier le schéma, la zone attendue et la lisibilité mobile avant publication.</p></div><Link className="secondary-button" to="/admin/visuels">Contrôler les visuels</Link></section>}
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Traçabilité</p><h2>État du contenu par année</h2></div><span className={summary.quality.published_without_source===0&&summary.quality.published_incomplete_source===0?'admin-ok':'admin-alert'}>{summary.quality.published_without_source===0&&summary.quality.published_incomplete_source===0?'Sources OK':'À contrôler'}</span></div><div className="admin-year-grid">{summary.years.map(year=><article key={year.study_year} className="admin-year-card"><strong>K{year.study_year}</strong><span>{year.published_questions} publiée{year.published_questions>1?'s':''}</span><small>{year.unpublished_questions} en préparation · {year.visual_pending} visuel{year.visual_pending>1?'s':''} non publié{year.visual_pending>1?'s':''}</small></article>)}</div>{summary.quality.published_without_source>0&&<p className="feedback-error">{summary.quality.published_without_source} question(s) publiée(s) sans source.</p>}{summary.quality.published_incomplete_source>0&&<p className="feedback-error">{summary.quality.published_incomplete_source} question(s) ont une source incomplète.</p>}</section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Revue pédagogique</p><h2>{review.counts.review+review.counts.validated} question{review.counts.review+review.counts.validated>1?'s':''} à contrôler</h2></div><span className="admin-alert">{review.counts.quarantined_visual} visuels en quarantaine</span></div><div className="admin-filters"><button className={reviewFilter==='all'?'active':''} onClick={()=>setReviewFilter('all')}>Toutes</button><button className={reviewFilter==='review'?'active':''} onClick={()=>setReviewFilter('review')}>À revoir · {review.counts.review}</button><button className={reviewFilter==='validated'?'active':''} onClick={()=>setReviewFilter('validated')}>Validées · {review.counts.validated}</button><button className={reviewFilter==='blocked'?'active':''} onClick={()=>setReviewFilter('blocked')}>Bloquées</button></div><div className="review-list">{reviewItems.length===0?<div className="admin-empty"><span>✓</span><strong>Aucune question dans cette file.</strong></div>:reviewItems.map(item=>{const readiness=reviewReadiness(item);return <article className="review-item" key={item.id}><div className="review-head"><div><span className="review-type">{typeLabel[item.type]??item.type}</span><strong>K{item.year_number} · {item.subject_name}</strong></div><span className={readiness.ready?'admin-ok':'admin-alert'}>{readiness.reason}</span></div><h3>{item.question_text}</h3><p className="review-path">{item.chapter_name} · {item.lesson_title}</p><div className="review-source"><strong>📚 {item.source_title??'Source absente'}</strong><span>{item.source_page?`Page ${item.source_page}`:'Page non renseignée'}</span>{item.source_excerpt&&<blockquote>{item.source_excerpt}</blockquote>}</div><div className="admin-feedback-actions"><span>Statut : {item.validation_status}</span>{item.validation_status==='review'&&<button className="secondary-button compact-button" disabled={!readiness.ready||busyId===item.id} onClick={()=>void changeContentStatus(item,'validated')}>Valider</button>}{item.validation_status==='validated'&&<button className="primary-button compact-button" disabled={!readiness.ready||busyId===item.id} onClick={()=>void changeContentStatus(item,'published')}>Publier</button>}{item.validation_status==='validated'&&<button className="text-link" disabled={busyId===item.id} onClick={()=>void changeContentStatus(item,'review')}>Renvoyer en revue</button>}</div></article>})}</div></section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Stabilité bêta</p><h2>Crashs applicatifs</h2></div><button className="text-link" onClick={()=>void load()}>Actualiser</button></div><div className="admin-feedback-list">{clientErrors.length===0?<div className="admin-empty"><span>✓</span><strong>Aucun crash React enregistré.</strong></div>:clientErrors.map(item=><article className="admin-feedback" key={item.id}><div className="admin-feedback-head"><div><span className="feedback-badge bug">Crash</span><strong>{item.user.first_name||item.user.username||'Utilisateur'}</strong></div><time>{new Date(item.created_at).toLocaleString('fr-FR')}</time></div><p>{item.message}</p>{item.page_path&&<code>{item.page_path}</code>}{item.component_stack&&<details><summary>Stack composant</summary><pre>{item.component_stack}</pre></details>}</article>)}</div></section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Tests utilisateurs</p><h2>Retours à traiter</h2></div><button className="text-link" onClick={()=>void load()}>Actualiser</button></div><div className="admin-filters"><button className={filter==='new'?'active':''} onClick={()=>void changeFilter('new')}>Nouveaux · {summary.feedback.new_feedback}</button><button className={filter==='reviewed'?'active':''} onClick={()=>void changeFilter('reviewed')}>Revus · {summary.feedback.reviewed_feedback}</button><button className={filter==='resolved'?'active':''} onClick={()=>void changeFilter('resolved')}>Résolus · {summary.feedback.resolved_feedback}</button><button className={filter===null?'active':''} onClick={()=>void changeFilter(null)}>Tous</button></div>{error&&<p className="feedback-error">{error}</p>}<div className="admin-feedback-list">{items.length===0?<div className="admin-empty"><span>✓</span><strong>Aucun retour dans cette file.</strong></div>:items.map(item=><article className="admin-feedback" key={item.id}><div className="admin-feedback-head"><div><span className={`feedback-badge ${item.kind}`}>{kindLabel[item.kind]}</span><strong>{item.user.first_name||item.user.username||'Utilisateur'}</strong></div><time>{new Date(item.created_at).toLocaleString('fr-FR')}</time></div><p>{item.message}</p>{item.page_path&&<code>{item.page_path}</code>}<div className="admin-feedback-actions"><span>{statusLabel[item.status]}</span>{item.status!=='reviewed'&&<button className="secondary-button compact-button" disabled={busyId===item.id} onClick={()=>void changeStatus(item.id,'reviewed')}>Marquer revu</button>}{item.status!=='resolved'&&<button className="primary-button compact-button" disabled={busyId===item.id} onClick={()=>void changeStatus(item.id,'resolved')}>Résoudre</button>}{item.status==='resolved'&&<button className="text-link" disabled={busyId===item.id} onClick={()=>void changeStatus(item.id,'new')}>Rouvrir</button>}</div></article>)}</div></section>
 </div>
}
