import { useEffect,useState } from 'react'
import { getContentQualitySummary,getFeedbackQueue,setFeedbackStatus,type FeedbackItem,type FeedbackStatus,type QualitySummary } from '../services/adminApi'
import './AdminPage.css'

const kindLabel={bug:'Bug',content:'Contenu',suggestion:'Suggestion'} as const
const statusLabel:Record<FeedbackStatus,string>={new:'Nouveau',reviewed:'Revu',resolved:'Résolu'}

export default function AdminPage(){
 const [summary,setSummary]=useState<QualitySummary|null>(null)
 const [items,setItems]=useState<FeedbackItem[]>([])
 const [filter,setFilter]=useState<FeedbackStatus|null>('new')
 const [busyId,setBusyId]=useState<string|null>(null)
 const [error,setError]=useState<string|null>(null)
 async function load(status=filter){setError(null);try{const [s,f]=await Promise.all([getContentQualitySummary(),getFeedbackQueue(status,100)]);setSummary(s);setItems(f)}catch(e){setError(e instanceof Error?e.message:'Impossible de charger l’administration.')}}
 useEffect(()=>{void load()},[])
 async function changeStatus(id:string,status:FeedbackStatus){setBusyId(id);try{await setFeedbackStatus(id,status);await load(filter)}catch(e){setError(e instanceof Error?e.message:'Impossible de mettre à jour ce retour.')}finally{setBusyId(null)}}
 async function changeFilter(status:FeedbackStatus|null){setFilter(status);setError(null);try{setItems(await getFeedbackQueue(status,100))}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les retours.')}}
 if(error&&!summary)return <section className="card"><p className="eyebrow">Administration</p><h1>Accès indisponible</h1><p>{error}</p></section>
 if(!summary)return <section className="card"><p>Chargement du centre de contrôle…</p></section>
 return <div className="stack admin-stack">
  <section className="hero-card"><div className="hero-copy"><span className="hero-kicker">Administration</span><h1>Qualité & retours Kineo</h1><p>Contrôle la traçabilité pédagogique et traite les anomalies remontées pendant les tests.</p></div><div className="hero-orbit"><span>✓</span></div></section>
  <section className="admin-metrics"><article className="metric-card"><span className="metric-icon">📚</span><div><small>Questions publiées</small><strong>{summary.quality.published_total}</strong></div></article><article className="metric-card"><span className="metric-icon">📄</span><div><small>CM validés</small><strong>{summary.documents.validated}/{summary.documents.total}</strong></div></article><article className="metric-card"><span className="metric-icon">⚠</span><div><small>Visuels en quarantaine</small><strong>{summary.quality.visual_quarantined}</strong></div></article><article className="metric-card"><span className="metric-icon">💬</span><div><small>Nouveaux retours</small><strong>{summary.feedback.new_feedback}</strong></div></article></section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Traçabilité</p><h2>État du contenu par année</h2></div><span className={summary.quality.published_without_source===0&&summary.quality.published_incomplete_source===0?'admin-ok':'admin-alert'}>{summary.quality.published_without_source===0&&summary.quality.published_incomplete_source===0?'Sources OK':'À contrôler'}</span></div><div className="admin-year-grid">{summary.years.map(year=><article key={year.study_year} className="admin-year-card"><strong>K{year.study_year}</strong><span>{year.published_questions} publiée{year.published_questions>1?'s':''}</span><small>{year.unpublished_questions} en préparation · {year.visual_pending} visuel{year.visual_pending>1?'s':''} non publié{year.visual_pending>1?'s':''}</small></article>)}</div>{summary.quality.published_without_source>0&&<p className="feedback-error">{summary.quality.published_without_source} question(s) publiée(s) sans source.</p>}{summary.quality.published_incomplete_source>0&&<p className="feedback-error">{summary.quality.published_incomplete_source} question(s) ont une source incomplète.</p>}</section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Tests utilisateurs</p><h2>Retours à traiter</h2></div><button className="text-link" onClick={()=>void load()}>Actualiser</button></div><div className="admin-filters"><button className={filter==='new'?'active':''} onClick={()=>void changeFilter('new')}>Nouveaux · {summary.feedback.new_feedback}</button><button className={filter==='reviewed'?'active':''} onClick={()=>void changeFilter('reviewed')}>Revus · {summary.feedback.reviewed_feedback}</button><button className={filter==='resolved'?'active':''} onClick={()=>void changeFilter('resolved')}>Résolus · {summary.feedback.resolved_feedback}</button><button className={filter===null?'active':''} onClick={()=>void changeFilter(null)}>Tous</button></div>{error&&<p className="feedback-error">{error}</p>}<div className="admin-feedback-list">{items.length===0?<div className="admin-empty"><span>✓</span><strong>Aucun retour dans cette file.</strong></div>:items.map(item=><article className="admin-feedback" key={item.id}><div className="admin-feedback-head"><div><span className={`feedback-badge ${item.kind}`}>{kindLabel[item.kind]}</span><strong>{item.user.first_name||item.user.username||'Utilisateur'}</strong></div><time>{new Date(item.created_at).toLocaleString('fr-FR')}</time></div><p>{item.message}</p>{item.page_path&&<code>{item.page_path}</code>}<div className="admin-feedback-actions"><span>{statusLabel[item.status]}</span>{item.status!=='reviewed'&&<button className="secondary-button compact-button" disabled={busyId===item.id} onClick={()=>void changeStatus(item.id,'reviewed')}>Marquer revu</button>}{item.status!=='resolved'&&<button className="primary-button compact-button" disabled={busyId===item.id} onClick={()=>void changeStatus(item.id,'resolved')}>Résoudre</button>}{item.status==='resolved'&&<button className="text-link" disabled={busyId===item.id} onClick={()=>void changeStatus(item.id,'new')}>Rouvrir</button>}</div></article>)}</div></section>
 </div>
}
