import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getCurrentProgram } from '../curriculum/programs'
import { getAccessiblePrograms, getCurriculumProgress, type AccessibleProgram, type CurriculumProgress } from '../services/programApi'
import './StatisticsPage.css'

export default function CurriculumStatisticsPage(){
 const program=getCurrentProgram()
 const isSpain=program.id==='kineo-es'
 const [access,setAccess]=useState<AccessibleProgram|null>(null)
 const [progress,setProgress]=useState<CurriculumProgress|null>(null)
 const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let cancelled=false;Promise.all([getAccessiblePrograms(),getCurriculumProgress(program.id)]).then(([items,nextProgress])=>{if(cancelled)return;setAccess(items.find(item=>item.program_id===program.id)??null);setProgress(nextProgress)}).catch((e:Error)=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[program.id])
 if(error)return <section className="card"><h1>{isSpain?'Estadísticas no disponibles':'Statistiques indisponibles'}</h1><p>{error}</p></section>
 if(!progress)return <section className="card skeleton-card"><p>{isSpain?'Calculando tu progreso…':'Calcul de ta progression…'}</p></section>
 const level=access?.level_code??'—',coverage=progress.coverage_percent??0,completion=progress.completion_percent??0,questionsTotal=progress.questions_total??0,questionsAnswered=progress.questions_answered??0,topicsTotal=progress.topics_total??0,topicsCompleted=progress.topics_completed??0
 const questionsRemaining=Math.max(0,questionsTotal-questionsAnswered),topicsRemaining=Math.max(0,topicsTotal-topicsCompleted)
 const curriculumLabel=program.id==='ifsi-fr'?' · Réf. '+(access?.curriculum_version==='2026'?'2026':'2009'):''
 return <div className="stack">
  <section className="stats-hero"><div className="stats-hero-copy"><p className="eyebrow light">{(isSpain?'Nivel ':'Niveau ')+level+curriculumLabel}</p><h1>{isSpain?'Tu progreso de un vistazo':'Ta progression en un coup d’œil'}</h1><p>{isSpain?'Visualiza lo trabajado, lo completado y lo que queda por revisar en tu nivel actual.':'Visualise ce qui est travaillé, terminé et ce qu’il reste à réviser sur ton niveau actuel.'}</p><div className="stats-hero-metrics"><span><small>{isSpain?'Cobertura':'Couverture'}</small><strong>{coverage}%</strong></span><span><small>{isSpain?'Finalización':'Complétion'}</small><strong>{completion}%</strong></span><span><small>{isSpain?'Preguntas':'Questions'}</small><strong>{questionsAnswered}/{questionsTotal}</strong></span><span><small>{isSpain?'Temas':'Thèmes'}</small><strong>{topicsCompleted}/{topicsTotal}</strong></span></div></div><div className="stats-hero-score"><span>{isSpain?'Nivel':'Niveau'}</span><strong>{level}</strong></div></section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Avance':'Avancement'}</p><h2>{isSpain?'Cobertura del nivel':'Couverture du niveau'}</h2></div><span className="activity-caption">{coverage}%</span></div><div className="progress-track"><div className="progress-fill" style={{width:Math.min(100,coverage)+'%'}}/></div></section>
  <section className="card focus-card"><div><p className="eyebrow">{isSpain?'A trabajar ahora':'À travailler maintenant'}</p><h2>{questionsRemaining>0?(isSpain?questionsRemaining+' preguntas por trabajar':questionsRemaining+' question'+(questionsRemaining>1?'s':'')+' à travailler'):(isSpain?'Nivel cubierto':'Niveau couvert')}</h2><p>{topicsRemaining>0?(isSpain?topicsRemaining+' temas todavía no completados.':topicsRemaining+' thème'+(topicsRemaining>1?'s':'')+' encore à terminer.'):(isSpain?'Todos los temas publicados de este nivel están completados.':'Tous les thèmes publiés de ce niveau sont terminés.')}</p>{(questionsRemaining>0||topicsRemaining>0)&&<Link className="secondary-button stats-focus-action" to="/parcours">{isSpain?'Continuar mi programa':'Continuer mon parcours'}</Link>}</div><div className="focus-bubble">💡</div></section>
  <section className="stats-grid"><article className="card score-card"><span>❓ {isSpain?'Preguntas trabajadas':'Questions travaillées'}</span><strong>{questionsAnswered}</strong><small>{isSpain?'de '+questionsTotal+' disponibles':'sur '+questionsTotal+' disponibles'}</small></article><article className="card score-card"><span>✅ {isSpain?'Temas completados':'Thèmes terminés'}</span><strong>{topicsCompleted}</strong><small>{isSpain?'de '+topicsTotal+' publicados':'sur '+topicsTotal+' publiés'}</small></article><article className="card score-card"><span>↗ {isSpain?'Finalización':'Complétion'}</span><strong>{completion}%</strong><small>{isSpain?'del nivel activo':'du niveau actif'}</small></article><article className="card score-card"><span>▦ {isSpain?'Nivel':'Niveau'}</span><strong>{level}</strong><small>{program.name}</small></article></section>
  <section className="quick-grid"><Link className="quick-card" to="/parcours"><span>▦</span><strong>{isSpain?'Programa':'Parcours'}</strong><small>{isSpain?'Materias, fichas y práctica':'UE, fiches et exercices'}</small></Link><Link className="quick-card" to="/fondamentaux"><span>✦</span><strong>{isSpain?'Repasar':'Réviser'}</strong><small>{isSpain?'Fundamentos y mezcla acumulativa':'Fondamentaux et mix cumulatif'}</small></Link><Link className="quick-card" to="/rewards"><span>★</span><strong>{isSpain?'Logros':'Badges'}</strong><small>{isSpain?'XP y recompensas':'XP et récompenses'}</small></Link><Link className="quick-card" to="/amis"><span>⚔️</span><strong>{isSpain?'Amigos y retos':'Amis & défis'}</strong><small>{isSpain?'Comparte y compite':'Partager et se challenger'}</small></Link></section>
 </div>
}
