import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { getAccessiblePrograms,getCurriculumStats,type AccessibleProgram,type CurriculumStats } from '../services/programApi'
import './StatisticsPage.css'
export default function CurriculumStatisticsPage(){
 const [access,setAccess]=useState<AccessibleProgram|null>(null),[stats,setStats]=useState<CurriculumStats|null>(null),[days,setDays]=useState(30),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let stop=false;setStats(null);getAccessiblePrograms().then(async xs=>{const p=xs.find(x=>x.is_primary);if(!p)throw new Error('Profil de formation non configuré.');const s=await getCurriculumStats(p.program_id,days);if(!stop){setAccess(p);setStats(s)}}).catch((e:Error)=>!stop&&setError(e.message));return()=>{stop=true}},[days])
 const isSpain=access?.program_id==='kineo-es',label=access?.program_id==='kineo-es'?'Kiné Espagne':access?.program_id==='ifsi-fr'?'IFSI France':'Kiné France'
 const max=useMemo(()=>Math.max(1,...(stats?.daily_activity??[]).map(x=>x.attempts)),[stats])
 if(error)return <section className="card"><h1>Statistiques indisponibles</h1><p>{error}</p></section>
 if(!stats||!access)return <section className="card skeleton-card"><p>Calcul de ta progression…</p></section>
 const s=stats.summary
 return <div className="stack stats-mobile"><header className="stats-page-head"><div><h1>{isSpain?'Mis estadísticas':'Mes statistiques'}</h1><p>{isSpain?'Visualiza tus progresos y mantén el ritmo.':'Visualise tes progrès et garde le rythme.'}</p></div><div className="stats-header-actions"><span className="profile-context">{label} · {access.level_code??'—'}</span><Link className="stats-badges-link" to="/rewards">{isSpain?'◆ Mis logros':'◆ Mes badges'}</Link></div></header>
 <section className="stats-overview card"><div className="progress-ring" style={{'--progress':Math.min(100,s.coverage_percent)} as React.CSSProperties}><div><strong>{s.coverage_percent}%</strong><span>{isSpain?'progreso':'progression'}</span></div></div><div className="overview-copy"><p className="eyebrow">{isSpain?'Progreso global':'Progression globale'}</p><h2>{s.questions_answered}/{s.questions_total} {isSpain?'preguntas descubiertas':'questions découvertes'}</h2><div className="progress-track"><div className="progress-fill" style={{width:s.coverage_percent+'%'}}/></div></div></section>
 <section className="stats-kpi-grid"><article className="card stat-kpi"><span>🔥</span><strong>{s.streak_current}</strong><small>{isSpain?'Días de racha':'Jours de série'}</small></article><article className="card stat-kpi"><span>✦</span><strong>{s.xp_total}</strong><small>XP</small></article><article className="card stat-kpi"><span>✓</span><strong>{s.accuracy_percent}%</strong><small>{isSpain?'Aciertos':'Taux de réussite'}</small></article><article className="card stat-kpi"><span>❓</span><strong>{s.attempts}</strong><small>{isSpain?'Respuestas':'Réponses'}</small></article><article className="card stat-kpi"><span>✓</span><strong>{s.correct_answers}</strong><small>{isSpain?'Correctas':'Bonnes réponses'}</small></article><article className="card stat-kpi"><span>↗</span><strong>+{s.xp_period}</strong><small>XP · {days} j</small></article></section>
 <section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Mi progreso':'Ma progression'}</p><h2>{isSpain?'Evolución':'Évolution'}</h2></div><div className="period-tabs">{[[7,'7 jours'],[30,'30 jours'],[90,'3 mois']].map(([d,l])=><button key={d} className={days===d?'active':''} onClick={()=>setDays(Number(d))}>{isSpain?(d===7?'7 días':d===30?'30 días':'3 meses'):l}</button>)}</div></div><div className="activity-chart">{stats.daily_activity.map(x=><div className="activity-day" key={x.date} title={x.date+' · '+x.attempts}><div className="activity-bar-wrap"><div className="activity-bar" style={{height:Math.max(8,Math.round(x.attempts/max*100))+'%'}}/></div><span>{new Date(x.date+'T12:00').toLocaleDateString(isSpain?'es-ES':'fr-FR',{weekday:'narrow'})}</span></div>)}</div></section>
 <section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Por asignatura':'Par matière'}</p><h2>{isSpain?'Resultados del nivel':'Résultats du niveau'}</h2></div></div><div className="subject-list">{stats.units.map(u=><article className="subject-progress" key={u.id}><div className="subject-row"><div><strong>{u.name}</strong><span>{u.questions_answered}/{u.questions_total} {isSpain?'preguntas vistas':'questions vues'}</span></div><div className="subject-score"><strong>{u.accuracy_percent}%</strong><span>{isSpain?'aciertos':'réussite'}</span></div></div><div className="progress-track small"><div className="progress-fill" style={{width:u.coverage_percent+'%'}}/></div></article>)}</div></section>
 <section className="card stats-goal"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Objetivo semanal':'Objectif hebdomadaire'}</p><h2>{isSpain?'Mantener el ritmo':'Garder le rythme'}</h2></div><strong>{s.streak_current} 🔥</strong></div><p>{isSpain?'Tu actividad real alimenta automáticamente este seguimiento.':'Ton activité réelle alimente automatiquement ce suivi.'}</p></section></div>
}