import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { getCurrentProgram } from '../curriculum/programs'
import { getAccessiblePrograms, getCurriculumProgress, type AccessibleProgram, type CurriculumProgress } from '../services/programApi'
import './StatisticsPage.css'

export default function CurriculumStatisticsPage(){
 const program=getCurrentProgram(),isSpain=program.id==='kineo-es'
 const [access,setAccess]=useState<AccessibleProgram|null>(null),[progress,setProgress]=useState<CurriculumProgress|null>(null),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let cancelled=false;getAccessiblePrograms().then(async items=>{if(cancelled)return;const primary=items.find(x=>x.is_primary)??items.find(x=>x.program_id===program.id)??null;if(!primary)throw new Error(isSpain?'Perfil de estudios no configurado.':'Profil de formation non configuré.');const p=await getCurriculumProgress(primary.program_id);if(!cancelled){setAccess(primary);setProgress(p)}}).catch((e:Error)=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[program.id,isSpain])
 const data=useMemo(()=>{if(!progress)return null;const q=progress.questions_total??0,a=progress.questions_answered??0,t=progress.topics_total??0,c=progress.topics_completed??0;return{q,a,t,c,coverage:progress.coverage_percent??0,completion:progress.completion_percent??0,remaining:Math.max(0,q-a)}},[progress])
 if(error)return <section className="card"><h1>{isSpain?'Estadísticas no disponibles':'Statistiques indisponibles'}</h1><p>{error}</p></section>
 if(!data||!access)return <section className="card skeleton-card"><p>{isSpain?'Calculando tu progreso…':'Calcul de ta progression…'}</p></section>
 const label=access.program_id==='kineo-es'?'Kiné Espagne':access.program_id==='ifsi-fr'?'IFSI France':'Kiné France',level=access.level_code??'—'
 return <div className="stack stats-mobile">
  <header className="stats-page-head"><div><h1>{isSpain?'Mis estadísticas':'Mes statistiques'}</h1><p>{isSpain?'Visualiza tus progresos y mantén el ritmo.':'Visualise tes progrès et garde le rythme.'}</p></div><span className="profile-context">{label} · {level}</span></header>
  <section className="stats-overview card"><div className="progress-ring" style={{'--progress':Math.min(100,data.completion)} as React.CSSProperties}><div><strong>{data.completion}%</strong><span>{isSpain?'progreso':'progression'}</span></div></div><div className="overview-copy"><p className="eyebrow">{isSpain?'Progreso global':'Progression globale'}</p><h2>{data.remaining?isSpain?`${data.remaining} preguntas por descubrir`:`${data.remaining} questions à découvrir`:isSpain?'Nivel completado':'Niveau complété'}</h2><p>{data.c}/{data.t} {isSpain?'temas completados':'thèmes terminés'} · {data.a}/{data.q} {isSpain?'preguntas trabajadas':'questions travaillées'}</p><div className="progress-track"><div className="progress-fill" style={{width:Math.min(100,data.coverage)+'%'}}/></div><small>{isSpain?'Cobertura del contenido':'Couverture du contenu'} · {data.coverage}%</small></div></section>
  <section className="stats-kpi-grid"><article className="card stat-kpi"><span>❓</span><strong>{data.a}</strong><small>{isSpain?'Preguntas respondidas':'Questions répondues'}</small></article><article className="card stat-kpi"><span>✓</span><strong>{data.c}</strong><small>{isSpain?'Temas dominados':'Thèmes maîtrisés'}</small></article><article className="card stat-kpi"><span>↗</span><strong>{data.completion}%</strong><small>{isSpain?'Finalización':'Complétion'}</small></article><article className="card stat-kpi"><span>▦</span><strong>{level}</strong><small>{isSpain?'Nivel actual':'Niveau actuel'}</small></article></section>
  <section className="card stats-goal"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Mi objetivo':'Mon objectif'}</p><h2>{isSpain?'Avanzar en mi nivel':'Avancer dans mon niveau'}</h2></div><strong>{data.coverage}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:Math.min(100,data.coverage)+'%'}}/></div><p>{data.remaining>0?(isSpain?`Todavía quedan ${data.remaining} preguntas disponibles.`:`Il reste ${data.remaining} questions disponibles.`):(isSpain?'Has cubierto todas las preguntas publicadas.':'Tu as couvert toutes les questions publiées.')}</p></section>
  <section className="stats-actions"><Link className="primary-button" to="/fondamentaux">{isSpain?'Continuar repasando':'Continuer à réviser'}</Link><Link className="secondary-button" to="/parcours">{isSpain?'Ver mis materias':'Voir mes matières'}</Link></section>
 </div>
}
