import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import InstallAppCard from '../components/InstallAppCard'
import { getFriendChallenges,type FriendChallenge } from '../services/challengeApi'
import { abandonRevisionSessionV1,getActiveRevisionSessionV1,getDashboardV2,getGamificationSummaryV2,getRecentRevisionSessionsV1,getRevisionModeAvailabilityV1,getStudyPrioritiesV1,type ActiveRevisionSession,type DashboardV2,type GamificationSummaryV2,type RevisionHistoryItem,type RevisionModeAvailability,type StudyPrioritiesV1 } from '../services/kineoApi'
import { getFriendships,type FriendshipsSummary } from '../services/socialApi'

const emptyFriends: FriendshipsSummary = { friends: [], incoming: [], outgoing: [] }
const ACTIVE_SMART_SESSION='kineo_active_smart_session'

export default function DashboardPage(){
 const [dashboard,setDashboard]=useState<DashboardV2|null>(null)
 const [game,setGame]=useState<GamificationSummaryV2|null>(null)
 const [modes,setModes]=useState<RevisionModeAvailability|null>(null)
 const [priorities,setPriorities]=useState<StudyPrioritiesV1|null>(null)
 const [active,setActive]=useState<ActiveRevisionSession|null>(null)
 const [recent,setRecent]=useState<RevisionHistoryItem[]>([])
 const [friends,setFriends]=useState<FriendshipsSummary>(emptyFriends)
 const [challenges,setChallenges]=useState<FriendChallenge[]>([])
 const [abandoning,setAbandoning]=useState(false)
 const [error,setError]=useState<string|null>(null)
 useEffect(()=>{Promise.all([getDashboardV2(),getGamificationSummaryV2(),getRevisionModeAvailabilityV1(),getStudyPrioritiesV1(),getActiveRevisionSessionV1(),getRecentRevisionSessionsV1(30),getFriendships('kineo-fr'),getFriendChallenges()]).then(([d,g,m,p,a,r,f,c])=>{setDashboard(d);setGame(g);setModes(m);setPriorities(p);setActive(a);setRecent(r);setFriends(f);setChallenges(c)}).catch((e:Error)=>setError(e.message))},[])
 const week=useMemo(()=>{const now=new Date(),day=(now.getDay()+6)%7,monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(now.getDate()-day);const sessions=recent.filter(r=>new Date(r.completed_at??r.started_at)>=monday);const activeDays=new Set(sessions.map(r=>new Date(r.completed_at??r.started_at).toISOString().slice(0,10))).size;return{sessions:sessions.length,activeDays,progress:Math.min(100,Math.round((sessions.length/5)*100))}},[recent])
 async function abandonActive(){if(!active)return;setAbandoning(true);try{await abandonRevisionSessionV1(active.id);localStorage.removeItem(ACTIVE_SMART_SESSION);setActive(null)}catch(e){setError(e instanceof Error?e.message:'Impossible d’abandonner cette session.')}finally{setAbandoning(false)}}
 if(error)return <section className="card"><h1>Progression indisponible</h1><p>{error}</p></section>
 if(!dashboard||!game||!modes||!priorities)return <section className="card skeleton-card"><p>Chargement de ta progression…</p></section>
 const xp=game.xp_total??dashboard.profile?.xp??0,level=game.level.number??dashboard.profile?.level??1,streak=game.streak.current??dashboard.streak?.current??0,mastery=dashboard.mastery?.overall_percent??0,dailyDone=dashboard.daily?.completed===true||dashboard.daily?.status==='completed',due=dashboard.mastery?.due??0
 const incomingChallenges=challenges.filter(item=>item.direction==='received'&&item.status==='pending')
 const playableChallenges=challenges.filter(item=>(item.status==='accepted'||item.status==='in_progress')&&!item.has_played)
 const waitingChallenges=challenges.filter(item=>item.has_played&&!item.opponent_has_played&&item.status!=='completed')
 const socialAttention=friends.incoming.length+incomingChallenges.length+playableChallenges.length
 const hasContent=modes.total_questions>0
 const studyYear=priorities.study_year??''
 return <div className="stack dashboard-stack">
  <section className="home-v4-welcome"><div><span className="eyebrow">✨ TON ESPACE KINEO</span><h1>Prêt pour une nouvelle session ? 👋</h1><p>Chaque petit progrès te rapproche de tes objectifs.</p></div></section><div className="home-v4-toprow"><section className="hero-card dashboard-daily-hero home-v3-hero"><div className="hero-copy"><span className="hero-kicker">{hasContent?`Aujourd’hui · Niveau ${level}`:`Parcours K${studyYear}`}</span><h1>{hasContent?(streak>0?`${streak} jour${streak>1?'s':''} de suite 🔥`:'Commence ta série aujourd’hui 🔥'):`Contenus K${studyYear} en préparation`}</h1><p>{hasContent?(due>0?`${due} notion${due>1?'s':''} à revoir aujourd’hui.`:'Ton programme est à jour. Quelques questions pour consolider ?'):'Aucune question validée n’est encore publiée pour cette année. Kineo n’utilisera pas de contenu non sourcé pour remplir artificiellement le parcours.'}</p>{hasContent&&<div className="hero-week-inline"><div className="hero-week-copy"><strong>Cette semaine</strong><span>{week.sessions} session{week.sessions>1?'s':''} · {week.activeDays} jour{week.activeDays>1?'s':''} actif{week.activeDays>1?'s':''}</span></div><div className="progress-track small"><div className="progress-fill" style={{width:`${week.progress}%`}}/></div><span className="hero-week-target">{week.sessions>=5?'Repère atteint ✓':`${5-week.sessions} session${5-week.sessions>1?'s':''} avant le repère`}</span></div>}{hasContent?<Link className="primary-button hero-action" to={dailyDone?'/revision':'/revision?mode=daily'}>{dailyDone?'Réviser · 10 questions':`Challenge du jour · ${dashboard.daily?.question_count??10} questions`}</Link>:<Link className="primary-button hero-action" to="/parcours">Voir le parcours</Link>}</div><div className="hero-orbit"><span>{hasContent?'🎓':'📚'}</span></div></section>
  <Link to="/rewards" className="card dashboard-level-card"><div className="dashboard-level-top"><span className="dashboard-level-emblem">🏅<small>NIVEAU</small>{level}</span><div><span className="eyebrow">Ton niveau XP</span><h2>Niveau {level} · {game.level.name}</h2><p>{xp} XP au total · {game.level.next_level?game.level.xp_to_next+' XP avant le prochain niveau':'Niveau maximum atteint'}</p></div><span className="dashboard-level-arrow">→</span></div><div className="progress-track"><div className="progress-fill" style={{width:Math.max(0,Math.min(100,game.level.progress_percent))+'%'}}/></div><small>Progression du niveau : {Math.round(game.level.progress_percent)}% · Voir mes badges</small></Link>
  </div>
  <div className="home-v3-shortcuts"><Link to="/revision" className="home-v3-shortcut"><span>📘</span><strong>Réviser</strong><small>Cours & QCM</small></Link><Link to="/amis" className="home-v3-shortcut home-social-shortcut" aria-label={socialAttention>0?`Défis entre amis, ${socialAttention} action${socialAttention>1?'s':''} en attente`:'Défis entre amis'}><span>🎯</span>{socialAttention>0&&<span className="home-social-count" aria-hidden="true">{socialAttention>99?'99+':socialAttention}</span>}<strong>Défis</strong><small>{socialAttention>0?`${socialAttention} action${socialAttention>1?'s':''} à traiter`:'Entre amis'}</small></Link><Link to="/rewards" className="home-v3-shortcut"><span>🏆</span><strong>Badges</strong><small>Récompenses</small></Link><Link to="/stats" className="home-v3-shortcut"><span>📊</span><strong>Statistiques</strong><small>Mes progrès</small></Link></div>
  <InstallAppCard/>
  {priorities.items.length>0&&<section className="card"><div className="section-heading"><div><p className="eyebrow">Priorités K{priorities.study_year??''}</p><h2>Ton plan de travail recommandé</h2></div><Link className="text-link" to="/parcours">Voir le parcours</Link></div><div className="people-list">{priorities.items.map((item,index)=><article className="person-row" key={item.subject_id}><div className="person-avatar">{item.icon||['🎯','📚','🧠'][index]}</div><div className="person-copy"><strong>{item.name}</strong><span>{item.reason} · maîtrise {item.mastery_percent}% · couverture {item.coverage_percent}%</span><div className="progress-track small"><div className="progress-fill" style={{width:`${Math.max(3,Math.min(100,item.coverage_percent))}%`}}/></div></div><Link className="secondary-button compact-button" to={`/revision-matiere?subjectId=${encodeURIComponent(item.subject_id)}&subject=${encodeURIComponent(item.name)}`}>Réviser</Link></article>)}</div></section>}

  {waitingChallenges.length>0&&<section className="card challenge-card done"><div className="challenge-icon">⏳</div><div className="challenge-copy"><p className="eyebrow">Défis</p><h2>{waitingChallenges.length} résultat{waitingChallenges.length>1?'s':''} en attente</h2><p>Ton score est enregistré. Kineo attend encore la réponse de ton adversaire.</p></div><Link className="text-link" to="/amis">Suivre</Link></section>}
  {active&&active.answered_count<active.question_count&&<section className="card challenge-card active-session-card"><div className="challenge-icon">▶</div><div className="challenge-copy"><p className="eyebrow">Session en cours</p><h2>Reprendre là où tu t’es arrêté</h2><p>{active.answered_count}/{active.question_count} questions déjà répondues · session synchronisée avec ton compte.</p></div><div className="friend-actions"><Link className="secondary-button" to={`/revision?mode=resume&session=${encodeURIComponent(active.id)}`}>Reprendre</Link><button className="text-link" onClick={()=>void abandonActive()} disabled={abandoning}>{abandoning?'…':'Abandonner'}</button></div></section>}
  <section className="dashboard-metrics"><article className="metric-card"><span className="metric-icon">⚡</span><div><small>XP</small><strong>{xp}</strong></div></article><article className="metric-card"><span className="metric-icon">🔥</span><div><small>Série</small><strong>{streak} j</strong></div></article><article className="metric-card"><span className="metric-icon">◉</span><div><small>Maîtrise</small><strong>{mastery}%</strong></div></article></section>
  <section className="card progress-card"><div className="section-heading"><div><p className="eyebrow">Connaissances</p><h2>Maîtrise du programme</h2></div><Link className="text-link" to="/stats">Détails</Link></div><div className="mastery-ring" style={{'--progress':`${Math.min(100,mastery)}%`} as React.CSSProperties}><span>{mastery}%</span></div><div className="progress-copy"><strong>{dashboard.mastery?.mastered??0} notions maîtrisées</strong><span>{dashboard.mastery?.fragile??0} fragiles · {due} à revoir</span></div></section>
  <section className="quick-grid"><Link className="quick-card" to="/parcours"><span>▦</span><strong>Parcours</strong><small>Choisir une leçon</small></Link>{modes.can_weak?<Link className="quick-card" to="/mes-erreurs"><span>🎯</span><strong>Mes points faibles</strong><small>{modes.weak_questions} notion{modes.weak_questions>1?'s':''} à retravailler</small></Link>:<div className="quick-card"><span>✅</span><strong>Points faibles</strong><small>{hasContent?'Rien d’urgent à retravailler':'Disponible après les premières révisions'}</small></div>}{modes.can_visual?<Link className="quick-card" to="/anatomie"><span>🦴</span><strong>Anatomie visuelle</strong><small>{modes.visual_questions} exercices disponibles</small></Link>:<div className="quick-card"><span>🦴</span><strong>Anatomie visuelle</strong><small>Contenu en validation pour ton année</small></div>}{modes.can_exam&&<Link className="quick-card" to="/examen"><span>📝</span><strong>Examen blanc</strong><small>20 questions équilibrées</small></Link>}<Link className="quick-card" to="/bibliotheque"><span>★</span><strong>Ma bibliothèque</strong><small>Favoris et notes personnelles</small></Link></section>
 </div>
}
