import { useEffect,useState } from 'react'
import { Link,useNavigate,useSearchParams } from 'react-router-dom'
import DuelHeadToHead from '../components/DuelHeadToHead'
import { cancelCurriculumFriendChallenge,cancelFriendChallenge,createCurriculumFriendChallenge,createFriendChallenge,getCurriculumChallengeAvailability,getCurriculumFriendChallenges,getFriendChallenges,respondCurriculumFriendChallenge,respondFriendChallenge,startFriendChallengeSession,type FriendChallenge } from '../services/challengeApi'
import { getCurrentProgram } from '../curriculum/programs'
import { getRevisionModeAvailabilityV1 } from '../services/kineoApi'
import { getCurrentProfile } from '../services/profileApi'
import { getFriendships,removeFriendship,respondFriendRequest,searchStudents,sendFriendRequest,type FriendshipsSummary,type SocialStudent } from '../services/socialApi'

const emptySummary:FriendshipsSummary={friends:[],incoming:[],outgoing:[]}
function duelOutcome(item:FriendChallenge,isSpain:boolean){const mine=item.direction==='sent'?item.challenger_score:item.challenged_score;const other=item.direction==='sent'?item.challenged_score:item.challenger_score;if(mine==null||other==null)return{label:isSpain?'Terminado':'Terminé',icon:'✓',className:'neutral'};if(mine>other)return{label:isSpain?'Victoria':'Victoire',icon:'🏆',className:'win'};if(mine<other)return{label:isSpain?'Derrota':'Défaite',icon:'💪',className:'loss'};return{label:isSpain?'Empate':'Égalité',icon:'🤝',className:'draw'}}

export default function FriendsPage(){
 const navigate=useNavigate();const[searchParams]=useSearchParams();const program=getCurrentProgram();const isKineoFrance=program.id==='kineo-fr';const isSpain=program.id==='kineo-es';const[summary,setSummary]=useState<FriendshipsSummary>(emptySummary);const[challenges,setChallenges]=useState<FriendChallenge[]>([]);const[results,setResults]=useState<SocialStudent[]>([]);const[query,setQuery]=useState('');const[hasUsername,setHasUsername]=useState<boolean|null>(null);const[canChallenge,setCanChallenge]=useState(false);const[challengeReadyCount,setChallengeReadyCount]=useState<number|null>(null);const[busyId,setBusyId]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState<string|null>(null)
 async function refresh(){
  const challengePromise=isKineoFrance?getFriendChallenges():getCurriculumFriendChallenges(program.id)
  const availabilityPromise=isKineoFrance?getRevisionModeAvailabilityV1().then(value=>({can:value.total_questions>=10,count:value.total_questions})):getCurriculumChallengeAvailability(program.id).then(value=>({can:value.can_challenge,count:value.validated_mcq}))
  const[profile,friendships,challengeRows,availability]=await Promise.all([getCurrentProfile(),getFriendships(program.id),challengePromise,availabilityPromise])
  setHasUsername(Boolean(profile?.username));setCanChallenge(availability.can);setChallengeReadyCount(availability.count);setSummary(friendships);setChallenges(challengeRows)
 }
 useEffect(()=>{
  const invited=searchParams.get('add')?.trim()??''
  setResults([]);setQuery(invited);setLoading(true)
  void refresh().then(async()=>{if(invited.length>=2){try{setResults(await searchStudents(invited,program.id));setMessage(isSpain?`Invitación recibida para @${invited}. Comprueba el perfil y añádelo a tus amigos.`:`Invitation reçue pour @${invited}. Vérifie le profil puis ajoute-le à tes amis.`)}catch{/* keep page usable */}}}).catch((e:Error)=>setMessage(e.message)).finally(()=>setLoading(false))
 },[program.id,searchParams])
 async function runSearch(e:React.FormEvent){e.preventDefault();setMessage(null);try{setResults(await searchStudents(query,program.id))}catch(err){setMessage(err instanceof Error?err.message:'Recherche impossible.')}}
 async function invite(student:SocialStudent){setBusyId(student.id);setMessage(null);try{await sendFriendRequest(student.id);setMessage(`Invitation envoyée à @${student.username} sur ${program.shortName}.`);setResults(v=>v.filter(x=>x.id!==student.id));await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible d’envoyer l’invitation.')}finally{setBusyId(null)}}
 async function answer(id:string,accept:boolean){setBusyId(id);setMessage(null);try{await respondFriendRequest(id,accept);setMessage(accept?'Invitation acceptée ✓':'Invitation refusée.');window.dispatchEvent(new Event('kineo-notifications-updated'));await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de traiter l’invitation.')}finally{setBusyId(null)}}
 async function remove(id:string,label:string){setBusyId(id);setMessage(null);try{await removeFriendship(id);setMessage(`${label} supprimé de tes amis.`);await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de supprimer cette relation.')}finally{setBusyId(null)}}
 async function cancelInvite(id:string){setBusyId(id);setMessage(null);try{await removeFriendship(id);setMessage('Invitation annulée.');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible d’annuler l’invitation.')}finally{setBusyId(null)}}
 async function challenge(friendId:string){setBusyId(friendId);setMessage(null);try{if(isKineoFrance)await createFriendChallenge(friendId);else await createCurriculumFriendChallenge(friendId,program.id);setMessage(`Défi ${program.shortName} envoyé ⚔️`);await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de lancer le défi.')}finally{setBusyId(null)}}
 async function answerChallenge(id:string,accept:boolean){setBusyId(id);setMessage(null);try{if(isKineoFrance)await respondFriendChallenge(id,accept);else await respondCurriculumFriendChallenge(id,accept);setMessage(accept?'Défi accepté. À toi de jouer !':'Défi refusé.');window.dispatchEvent(new Event('kineo-notifications-updated'));await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de traiter le défi.')}finally{setBusyId(null)}}
 async function cancelChallenge(id:string){setBusyId(id);setMessage(null);try{if(isKineoFrance)await cancelFriendChallenge(id);else await cancelCurriculumFriendChallenge(id);setMessage('Défi annulé.');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible d’annuler ce défi.')}finally{setBusyId(null)}}
 async function playChallenge(id:string){setBusyId(id);setMessage(null);try{if(isKineoFrance){const sessionId=await startFriendChallengeSession(id);navigate(`/revision?mode=challenge&session=${sessionId}&challenge=${id}`)}else navigate(`/defi-cursus/${id}`)}catch(err){setMessage(err instanceof Error?err.message:'Impossible de démarrer le défi.');setBusyId(null)}}
 if(loading)return<section className="card skeleton-card"><p>{isSpain?'Cargando tus amigos…':'Chargement de tes amis…'}</p></section>
 const active=challenges.filter(x=>!['completed','declined','cancelled'].includes(x.status));const completed=challenges.filter(x=>x.status==='completed').slice(0,5)
 const studyLabel=(student:SocialStudent)=>`${program.shortName} · ${student.level_code??(isKineoFrance&&student.study_year?`K${student.study_year}`:(isSpain?'nivel por definir':'niveau à définir'))}`
 return <div className="stack friends-stack">
  <section className="hero-card friends-hero"><div className="hero-copy"><span className="hero-kicker">{isSpain?'Repasar juntos':'Réviser ensemble'} · {program.shortName}</span><h1>{isSpain?'Amigos y retos ⚔️':'Amis & défis ⚔️'}</h1><p>{isSpain?'Esta página muestra únicamente a los estudiantes que comparten tu plan de estudios. Un duelo es posible cuando también estáis en el mismo nivel.':<>Cette page affiche uniquement les étudiants qui partagent le cursus <strong>{program.shortName}</strong>. Un duel est possible lorsque vous êtes aussi au même niveau.</>}</p><Link className="secondary-button" to="/classement">🏆 {isSpain?'Clasificación de la semana':'Classement de la semaine'}</Link></div><div className="hero-orbit" aria-hidden="true"><span>🤝</span></div></section>
  {!hasUsername&&<section className="card setup-card"><div><p className="eyebrow">{isSpain?'Antes de empezar':'Avant de commencer'}</p><h2>{isSpain?'Elige tu alias':'Choisis ton pseudo'}</h2><p>{isSpain?'Necesitas un alias para que otros estudiantes puedan encontrarte.':'Un pseudo est nécessaire pour que les autres étudiants puissent te retrouver.'}</p></div><Link className="primary-button" to="/profil">{isSpain?'Crear mi alias':'Créer mon pseudo'}</Link></section>}
  {active.length>0&&<section className="card challenge-hub-card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Duelos':'Duels'}</p><h2>{isSpain?'Retos en curso':'Défis en cours'}</h2></div><strong>{active.length}</strong></div><div className="people-list">{active.map(item=>{const awaitingMe=item.direction==='received'&&item.status==='pending';const sentPending=item.direction==='sent'&&item.status==='pending';const waiting=item.has_played&&!item.opponent_has_played;const playable=(item.status==='accepted'||item.status==='in_progress')&&!item.has_played;const scope=!isKineoFrance&&item.level_code?` · ${item.level_code}`:'';const status=item.status==='pending'?(awaitingMe?`te défie sur 10 questions${scope}`:'invitation envoyée'):waiting?'ton score est enregistré · en attente de ton ami':item.status==='in_progress'?`duel en cours${scope} · même quiz`:`même quiz${scope} · 10 questions`;return <article className="person-row challenge-row" key={item.id}><div className="person-avatar duel-avatar">{item.opponent.avatar_url?<img src={item.opponent.avatar_url} alt=""/>:(item.opponent.first_name||item.opponent.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{item.opponent.first_name||item.opponent.username}</strong><span>{status}</span></div>{awaitingMe?<div className="friend-actions"><button className="primary-button compact-button" onClick={()=>void answerChallenge(item.id,true)} disabled={busyId===item.id}>{isSpain?'Aceptar':'Accepter'}</button><button className="secondary-button compact-button" onClick={()=>void answerChallenge(item.id,false)} disabled={busyId===item.id}>{isSpain?'Rechazar':'Refuser'}</button></div>:sentPending?<button className="text-link" onClick={()=>void cancelChallenge(item.id)} disabled={busyId===item.id}>{isSpain?'Cancelar':'Annuler'}</button>:waiting?<span className="pending-chip">Résultat en attente</span>:playable?<button className="primary-button compact-button" onClick={()=>void playChallenge(item.id)} disabled={busyId===item.id}>{busyId===item.id?'…':'Jouer'}</button>:<span className="pending-chip">En attente</span>}</article>})}</div></section>}
  <section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Encontrar un compañero':'Trouver un camarade'}</p><h2>{isSpain?'Añadir un amigo':'Ajouter un ami'} · {program.shortName}</h2></div></div><p className="curriculum-empty">{isSpain?'Busca por alias o abre directamente el enlace/QR compartido por tu amigo.':'Recherche par pseudo, ou ouvre directement le lien/QR partagé par ton ami.'}</p><form className="friend-search" onSubmit={runSearch}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={isSpain?'Alias o nombre':'Pseudo ou prénom'} minLength={2}/><button className="primary-button" type="submit" disabled={query.trim().length<2}>{isSpain?'Buscar':'Rechercher'}</button></form>{results.length>0&&<div className="people-list">{results.map(student=><article className="person-row" key={student.id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><button className="secondary-button compact-button" onClick={()=>void invite(student)} disabled={busyId===student.id}>{busyId===student.id?'…':(isSpain?'Añadir':'Ajouter')}</button></article>)}</div>}</section>
  {summary.incoming.length>0&&<section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Por validar':'À valider'}</p><h2>{isSpain?'Invitaciones recibidas':'Invitations reçues'} · {program.shortName}</h2></div><strong>{summary.incoming.length}</strong></div><div className="people-list">{summary.incoming.map(student=><article className="person-row incoming" key={student.friendship_id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><div className="friend-actions"><button className="primary-button compact-button" onClick={()=>void answer(student.friendship_id,true)} disabled={busyId===student.friendship_id}>Accepter</button><button className="secondary-button compact-button" onClick={()=>void answer(student.friendship_id,false)} disabled={busyId===student.friendship_id}>Refuser</button></div></article>)}</div></section>}
  <section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Mi grupo':'Mon groupe'} · {program.shortName}</p><h2>{isSpain?'Mis amigos del programa':'Mes amis du cursus'}</h2></div><strong>{summary.friends.length}</strong></div>{summary.friends.length===0?<div className="empty-social"><span>👋</span><strong>{isSpain?'Todavía no tienes amigos en este programa':'Aucun ami dans ce cursus pour le moment'}</strong><p>{isSpain?`Busca a un compañero inscrito en ${program.shortName} o comparte tu QR desde tu perfil.`:`Recherche un camarade inscrit à ${program.shortName}, ou partage ton QR depuis ton profil.`}</p></div>:<div className="people-list">{summary.friends.map(student=>{const duelReady=Boolean(student.same_level)&&canChallenge;const unavailableLabel=isKineoFrance?'Défis bientôt disponibles':`${challengeReadyCount??0}/10 QCM ${isSpain?'validados':'validés'}`;const duelLabel=!student.same_level?`${isSpain?'Nivel diferente':'Niveau différent'} · ${student.level_code??(isSpain?'por definir':'à définir')}`:!canChallenge?unavailableLabel:(isSpain?'⚔️ Retar':'⚔️ Défier');return <article className="person-row" key={student.friendship_id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><div className="friend-actions"><button className="duel-button" onClick={()=>void challenge(student.id)} disabled={busyId===student.id||!duelReady}>{duelLabel}</button><button className="friend-remove-button" onClick={()=>void remove(student.friendship_id,student.first_name||student.username||'Ami')} disabled={busyId===student.friendship_id}>{isSpain?'Eliminar':'Retirer'}</button></div></article>})}</div>}</section>
  <DuelHeadToHead challenges={challenges}/>
  {completed.length>0&&<section className="card"><div className="section-heading"><div><p className="eyebrow">{isSpain?'Historial':'Historique'}</p><h2>{isSpain?'Últimos duelos':'Derniers duels'}</h2></div></div><div className="people-list">{completed.map(item=>{const mine=item.direction==='sent'?item.challenger_score:item.challenged_score;const other=item.direction==='sent'?item.challenged_score:item.challenger_score;const outcome=duelOutcome(item,isSpain);return <article className={`duel-result duel-${outcome.className}`} key={item.id}><div><strong>{outcome.icon} {outcome.label} · {item.opponent.first_name||item.opponent.username}</strong><span>@{item.opponent.username}{!isKineoFrance&&item.level_code?` · ${item.level_code}`:''}</span></div><div className="duel-score"><strong>{mine??'-'}%</strong><span>—</span><strong>{other??'-'}%</strong></div></article>})}</div></section>}
  {summary.outgoing.length>0&&<section className="card muted-card"><p className="eyebrow">{isSpain?'Pendiente':'En attente'} · {program.shortName}</p><h2>{isSpain?'Invitaciones enviadas':'Invitations envoyées'}</h2><div className="people-list">{summary.outgoing.map(student=><article className="person-row" key={student.friendship_id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><button className="text-link" onClick={()=>void cancelInvite(student.friendship_id)} disabled={busyId===student.friendship_id}>Annuler</button></article>)}</div></section>}
  {message&&<section className="card feedback-card"><p className="feedback">{message}</p></section>}
 </div>
}
