import { useEffect,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { cancelCurriculumFriendChallenge,cancelFriendChallenge,createCurriculumFriendChallenge,createFriendChallenge,getCurriculumChallengeAvailability,getCurriculumFriendChallenges,getFriendChallenges,respondCurriculumFriendChallenge,respondFriendChallenge,startFriendChallengeSession,type FriendChallenge } from '../services/challengeApi'
import { getCurrentProgram } from '../curriculum/programs'
import { getRevisionModeAvailabilityV1 } from '../services/kineoApi'
import { getCurrentProfile } from '../services/profileApi'
import { getFriendships,removeFriendship,respondFriendRequest,searchStudents,sendFriendRequest,type FriendshipsSummary,type SocialStudent } from '../services/socialApi'

const emptySummary:FriendshipsSummary={friends:[],incoming:[],outgoing:[]}
function duelOutcome(item:FriendChallenge){const mine=item.direction==='sent'?item.challenger_score:item.challenged_score;const other=item.direction==='sent'?item.challenged_score:item.challenger_score;if(mine==null||other==null)return{label:'Terminé',icon:'✓',className:'neutral'};if(mine>other)return{label:'Victoire',icon:'🏆',className:'win'};if(mine<other)return{label:'Défaite',icon:'💪',className:'loss'};return{label:'Égalité',icon:'🤝',className:'draw'}}

export default function FriendsPage(){
 const navigate=useNavigate();const program=getCurrentProgram();const isKineoFrance=program.id==='kineo-fr';const[summary,setSummary]=useState<FriendshipsSummary>(emptySummary);const[challenges,setChallenges]=useState<FriendChallenge[]>([]);const[results,setResults]=useState<SocialStudent[]>([]);const[query,setQuery]=useState('');const[hasUsername,setHasUsername]=useState<boolean|null>(null);const[canChallenge,setCanChallenge]=useState(false);const[challengeReadyCount,setChallengeReadyCount]=useState<number|null>(null);const[busyId,setBusyId]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState<string|null>(null)
 async function refresh(){
  const challengePromise=isKineoFrance?getFriendChallenges():getCurriculumFriendChallenges(program.id)
  const availabilityPromise=isKineoFrance
   ?getRevisionModeAvailabilityV1().then(value=>({can:value.total_questions>=10,count:value.total_questions}))
   :getCurriculumChallengeAvailability(program.id).then(value=>({can:value.can_challenge,count:value.validated_mcq}))
  const[profile,friendships,challengeRows,availability]=await Promise.all([getCurrentProfile(),getFriendships(program.id),challengePromise,availabilityPromise])
  setHasUsername(Boolean(profile?.username));setCanChallenge(availability.can);setChallengeReadyCount(availability.count);setSummary(friendships);setChallenges(challengeRows)
 }
 useEffect(()=>{setResults([]);setQuery('');setLoading(true);void refresh().catch((e:Error)=>setMessage(e.message)).finally(()=>setLoading(false))},[program.id])
 async function runSearch(e:React.FormEvent){e.preventDefault();setMessage(null);try{setResults(await searchStudents(query,program.id))}catch(err){setMessage(err instanceof Error?err.message:'Recherche impossible.')}}
 async function invite(student:SocialStudent){setBusyId(student.id);setMessage(null);try{await sendFriendRequest(student.id);setMessage(`Invitation envoyée à @${student.username} sur ${program.shortName}.`);setResults(v=>v.filter(x=>x.id!==student.id));await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible d’envoyer l’invitation.')}finally{setBusyId(null)}}
 async function answer(id:string,accept:boolean){setBusyId(id);setMessage(null);try{await respondFriendRequest(id,accept);setMessage(accept?'Invitation acceptée ✓':'Invitation refusée.');window.dispatchEvent(new Event('kineo-notifications-updated'));await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de traiter l’invitation.')}finally{setBusyId(null)}}
 async function remove(id:string,label:string){setBusyId(id);setMessage(null);try{await removeFriendship(id);setMessage(`${label} supprimé de tes amis.`);await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de supprimer cette relation.')}finally{setBusyId(null)}}
 async function cancelInvite(id:string){setBusyId(id);setMessage(null);try{await removeFriendship(id);setMessage('Invitation annulée.');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible d’annuler l’invitation.')}finally{setBusyId(null)}}
 async function challenge(friendId:string){setBusyId(friendId);setMessage(null);try{if(isKineoFrance)await createFriendChallenge(friendId);else await createCurriculumFriendChallenge(friendId,program.id);setMessage(`Défi ${program.shortName} envoyé ⚔️`);await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de lancer le défi.')}finally{setBusyId(null)}}
 async function answerChallenge(id:string,accept:boolean){setBusyId(id);setMessage(null);try{if(isKineoFrance)await respondFriendChallenge(id,accept);else await respondCurriculumFriendChallenge(id,accept);setMessage(accept?'Défi accepté. À toi de jouer !':'Défi refusé.');window.dispatchEvent(new Event('kineo-notifications-updated'));await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible de traiter le défi.')}finally{setBusyId(null)}}
 async function cancelChallenge(id:string){setBusyId(id);setMessage(null);try{if(isKineoFrance)await cancelFriendChallenge(id);else await cancelCurriculumFriendChallenge(id);setMessage('Défi annulé.');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Impossible d’annuler ce défi.')}finally{setBusyId(null)}}
 async function playChallenge(id:string){setBusyId(id);setMessage(null);try{if(isKineoFrance){const sessionId=await startFriendChallengeSession(id);navigate(`/revision?mode=challenge&session=${sessionId}&challenge=${id}`)}else navigate(`/defi-cursus/${id}`)}catch(err){setMessage(err instanceof Error?err.message:'Impossible de démarrer le défi.');setBusyId(null)}}
 if(loading)return<section className="card skeleton-card"><p>Chargement de tes amis…</p></section>
 const active=challenges.filter(x=>!['completed','declined','cancelled'].includes(x.status));const completed=challenges.filter(x=>x.status==='completed').slice(0,5)
 const studyLabel=(student:SocialStudent)=>`${program.shortName} · ${student.level_code??(isKineoFrance&&student.study_year?`K${student.study_year}`:'niveau à définir')}`
 return <div className="stack friends-stack">
  <section className="hero-card friends-hero"><div className="hero-copy"><span className="hero-kicker">Réviser ensemble · {program.shortName}</span><h1>Amis & défis ⚔️</h1><p>Cette page affiche uniquement les étudiants qui partagent le cursus <strong>{program.shortName}</strong>. Un duel est possible lorsque vous êtes aussi au même niveau.</p><Link className="secondary-button" to="/classement">🏆 Classement de la semaine</Link></div><div className="hero-orbit" aria-hidden="true"><span>🤝</span></div></section>
  {!hasUsername&&<section className="card setup-card"><div><p className="eyebrow">Avant de commencer</p><h2>Choisis ton pseudo</h2><p>Un pseudo est nécessaire pour que les autres étudiants puissent te retrouver.</p></div><Link className="primary-button" to="/profil">Créer mon pseudo</Link></section>}
  {active.length>0&&<section className="card challenge-hub-card"><div className="section-heading"><div><p className="eyebrow">Duels</p><h2>Défis en cours</h2></div><strong>{active.length}</strong></div><div className="people-list">{active.map(item=>{const awaitingMe=item.direction==='received'&&item.status==='pending';const sentPending=item.direction==='sent'&&item.status==='pending';const waiting=item.has_played&&!item.opponent_has_played;const playable=(item.status==='accepted'||item.status==='in_progress')&&!item.has_played;const scope=!isKineoFrance&&item.level_code?` · ${item.level_code}`:'';const status=item.status==='pending'?(awaitingMe?`te défie sur 10 questions${scope}`:'invitation envoyée'):waiting?'ton score est enregistré · en attente de ton ami':item.status==='in_progress'?`duel en cours${scope} · même quiz`:`même quiz${scope} · 10 questions`;return <article className="person-row challenge-row" key={item.id}><div className="person-avatar duel-avatar">{item.opponent.avatar_url?<img src={item.opponent.avatar_url} alt=""/>:(item.opponent.first_name||item.opponent.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{item.opponent.first_name||item.opponent.username}</strong><span>{status}</span></div>{awaitingMe?<div className="friend-actions"><button className="primary-button compact-button" onClick={()=>void answerChallenge(item.id,true)} disabled={busyId===item.id}>Accepter</button><button className="secondary-button compact-button" onClick={()=>void answerChallenge(item.id,false)} disabled={busyId===item.id}>Refuser</button></div>:sentPending?<button className="text-link" onClick={()=>void cancelChallenge(item.id)} disabled={busyId===item.id}>Annuler</button>:waiting?<span className="pending-chip">Résultat en attente</span>:playable?<button className="primary-button compact-button" onClick={()=>void playChallenge(item.id)} disabled={busyId===item.id}>{busyId===item.id?'…':'Jouer'}</button>:<span className="pending-chip">En attente</span>}</article>})}</div></section>}
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Trouver un camarade</p><h2>Ajouter un ami · {program.shortName}</h2></div></div><p className="curriculum-empty">La recherche est limitée aux étudiants inscrits dans ce cursus.</p><form className="friend-search" onSubmit={runSearch}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pseudo ou prénom" minLength={2}/><button className="primary-button" type="submit" disabled={query.trim().length<2}>Rechercher</button></form>{results.length>0&&<div className="people-list">{results.map(student=><article className="person-row" key={student.id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><button className="secondary-button compact-button" onClick={()=>void invite(student)} disabled={busyId===student.id}>{busyId===student.id?'…':'Ajouter'}</button></article>)}</div>}</section>
  {summary.incoming.length>0&&<section className="card"><div className="section-heading"><div><p className="eyebrow">À valider</p><h2>Invitations reçues · {program.shortName}</h2></div><strong>{summary.incoming.length}</strong></div><div className="people-list">{summary.incoming.map(student=><article className="person-row incoming" key={student.friendship_id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><div className="friend-actions"><button className="primary-button compact-button" onClick={()=>void answer(student.friendship_id,true)} disabled={busyId===student.friendship_id}>Accepter</button><button className="secondary-button compact-button" onClick={()=>void answer(student.friendship_id,false)} disabled={busyId===student.friendship_id}>Refuser</button></div></article>)}</div></section>}
  <section className="card"><div className="section-heading"><div><p className="eyebrow">Mon groupe · {program.shortName}</p><h2>Mes amis du cursus</h2></div><strong>{summary.friends.length}</strong></div>{summary.friends.length===0?<div className="empty-social"><span>👋</span><strong>Aucun ami dans ce cursus pour le moment</strong><p>Recherche un camarade inscrit à {program.shortName}, ou change de cursus pour retrouver les amis d’un autre parcours.</p></div>:<div className="people-list">{summary.friends.map(student=>{const duelReady=Boolean(student.same_level)&&canChallenge;const unavailableLabel=isKineoFrance?'Défis bientôt disponibles':`${challengeReadyCount??0}/10 QCM validés`;const duelLabel=!student.same_level?`Niveau différent · ${student.level_code??'à définir'}`:!canChallenge?unavailableLabel:'⚔️ Défier';return <article className="person-row" key={student.friendship_id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><div className="friend-actions"><button className="duel-button" onClick={()=>void challenge(student.id)} disabled={busyId===student.id||!duelReady}>{duelLabel}</button><button className="friend-remove-button" onClick={()=>void remove(student.friendship_id,student.first_name||student.username||'Ami')} disabled={busyId===student.friendship_id}>Retirer</button></div></article>})}</div>}</section>
  {completed.length>0&&<section className="card"><div className="section-heading"><div><p className="eyebrow">Historique</p><h2>Derniers duels</h2></div></div><div className="people-list">{completed.map(item=>{const mine=item.direction==='sent'?item.challenger_score:item.challenged_score;const other=item.direction==='sent'?item.challenged_score:item.challenger_score;const outcome=duelOutcome(item);return <article className={`duel-result duel-${outcome.className}`} key={item.id}><div><strong>{outcome.icon} {outcome.label} · {item.opponent.first_name||item.opponent.username}</strong><span>@{item.opponent.username}{!isKineoFrance&&item.level_code?` · ${item.level_code}`:''}</span></div><div className="duel-score"><strong>{mine??'-'}%</strong><span>—</span><strong>{other??'-'}%</strong></div></article>})}</div></section>}
  {summary.outgoing.length>0&&<section className="card muted-card"><p className="eyebrow">En attente · {program.shortName}</p><h2>Invitations envoyées</h2><div className="people-list">{summary.outgoing.map(student=><article className="person-row" key={student.friendship_id}><div className="person-avatar">{student.avatar_url?<img src={student.avatar_url} alt=""/>:(student.first_name||student.username||'?').slice(0,1).toUpperCase()}</div><div className="person-copy"><strong>{student.first_name||student.username}</strong><span>@{student.username} · {studyLabel(student)}</span></div><button className="text-link" onClick={()=>void cancelInvite(student.friendship_id)} disabled={busyId===student.friendship_id}>Annuler</button></article>)}</div></section>}
  {message&&<section className="card feedback-card"><p className="feedback">{message}</p></section>}
 </div>
}
