import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { ReadableCourseContent } from '../components/ReadableCourseContent'
import { getLessonV2,startLessonQuizV2,type LessonV2 } from '../services/curriculumApi'
import { getLessonPersonalState,saveLessonNote,toggleLessonFavorite } from '../services/libraryApi'
import { getCurrentProfile } from '../services/profileApi'
import '../course-reading.css'
import './LessonPage.css'

function renderListItem(value:unknown,index:number){if(typeof value==='string')return<li key={index}>{value}</li>;if(value&&typeof value==='object')return<li key={index}>{JSON.stringify(value)}</li>;return null}
function pageLabel(start:number|null,end:number|null){if(start==null)return null;if(end!=null&&end!==start)return`pages ${start}–${end}`;return`page ${start}`}

export default function LessonPage(){
 const{lessonId}=useParams();const navigate=useNavigate();const[lesson,setLesson]=useState<LessonV2|null>(null);const[profileYear,setProfileYear]=useState<number|null>(null);const[favorite,setFavorite]=useState(false);const[note,setNote]=useState('');const[noteSaved,setNoteSaved]=useState(true);const[busy,setBusy]=useState(false);const[personalBusy,setPersonalBusy]=useState(false);const[error,setError]=useState<string|null>(null)
 useEffect(()=>{if(!lessonId)return;Promise.all([getLessonV2(lessonId),getLessonPersonalState(lessonId),getCurrentProfile()]).then(([lessonData,state,profile])=>{setLesson(lessonData);setFavorite(state.favorite);setNote(state.note??'');setProfileYear(profile?.study_year??null)}).catch((err:Error)=>setError(err.message))},[lessonId])
 async function launchQuiz(){if(!lesson)return;setBusy(true);setError(null);try{const sessionId=await startLessonQuizV2(lesson.id,10);navigate(`/revision?mode=lesson&session=${encodeURIComponent(sessionId)}`)}catch(err){setError(err instanceof Error?err.message:'Impossible de démarrer le quiz.')}finally{setBusy(false)}}
 async function toggleFavorite(){if(!lesson)return;setPersonalBusy(true);try{setFavorite(await toggleLessonFavorite(lesson.id))}catch(err){setError(err instanceof Error?err.message:'Impossible de modifier le favori.')}finally{setPersonalBusy(false)}}
 async function saveNote(){if(!lesson)return;setPersonalBusy(true);try{setNote(await saveLessonNote(lesson.id,note));setNoteSaved(true)}catch(err){setError(err instanceof Error?err.message:'Impossible d’enregistrer la note.')}finally{setPersonalBusy(false)}}
 if(error&&!lesson)return<section className="card"><h1>Leçon indisponible</h1><p>{error}</p><Link className="secondary-button" to="/parcours">Retour au parcours</Link></section>
 if(!lesson)return<section className="card skeleton-card"><p>Chargement de la leçon…</p></section>
 const canQuiz=profileYear===lesson.year.number
 return <div className="stack">
  <section className="stats-hero"><div><p className="eyebrow light">K{lesson.year.number} · {lesson.subject.icon?`${lesson.subject.icon} `:''}{lesson.subject.name}</p><h1>{lesson.title}</h1><p>{lesson.chapter.name}{lesson.summary?` · ${lesson.summary}`:''}</p><button className={`lesson-favorite ${favorite?'active':''}`} onClick={()=>void toggleFavorite()} disabled={personalBusy}>{favorite?'★ Enregistré dans mes favoris':'☆ Ajouter aux favoris'}</button></div><div className="stats-hero-score"><span>Maîtrise</span><strong>{lesson.mastery_percent}%</strong></div></section>
  {!canQuiz&&profileYear&&<section className="card muted-card"><p className="eyebrow">Consultation</p><h2>Leçon K{lesson.year.number}</h2><p>Ton profil est actuellement en K{profileYear}. Tu peux lire et annoter cette leçon, mais les quiz restent réservés à ton année active.</p></section>}
  <section className="stats-grid"><article className="card score-card"><span>❓ Questions</span><strong>{lesson.question_count}</strong><small>validées et jouables</small></article><article className="card score-card"><span>🧠 Maîtrise</span><strong>{lesson.mastery_percent}%</strong><small>progression actuelle</small></article><article className="card score-card"><span>🎯 Quiz</span><strong>{Math.min(10,lesson.question_count)}</strong><small>{canQuiz?'questions proposées':`réservé K${lesson.year.number}`}</small></article><article className="card score-card"><span>✅ Statut</span><strong>Validé</strong><small>contenu publié</small></article></section>
  {lesson.image_url&&<section className="card centered"><img className="question-image" src={lesson.image_url} alt="Illustration de la leçon"/></section>}
  {lesson.content&&<section className="card lesson-course-card"><div className="section-heading"><div><p className="eyebrow">Cours</p><h2>Comprendre et mémoriser</h2></div></div><div className="course-reading-shell"><ReadableCourseContent content={lesson.content}/></div></section>}
  {lesson.key_points.length>0&&<section className="card focus-card lesson-key-points-card"><div><p className="eyebrow">Points clés</p><h2>À retenir</h2><ul>{lesson.key_points.map(renderListItem)}</ul></div><div className="focus-bubble">✓</div></section>}
  <section className="card lesson-note-card"><div className="section-heading"><div><p className="eyebrow">Note personnelle</p><h2>Mon aide-mémoire</h2></div><Link className="text-link" to="/bibliotheque">Ma bibliothèque</Link></div><textarea value={note} maxLength={4000} onChange={e=>{setNote(e.target.value);setNoteSaved(false)}} placeholder="Ajoute ici un moyen mnémotechnique, une définition à retenir ou un point à revoir…"/><div className="lesson-note-footer"><small>{note.length}/4000{noteSaved?' · enregistré':''}</small><button className="secondary-button compact-button" onClick={()=>void saveNote()} disabled={personalBusy||noteSaved}>{personalBusy?'Enregistrement…':'Enregistrer la note'}</button></div></section>
  {lesson.source_documents.length>0&&<section className="card lesson-reference-strip"><div className="section-heading"><div><p className="eyebrow">Traçabilité</p><h2>Support pédagogique validé</h2></div><span className="status-dot">Validé</span></div><div className="people-list">{lesson.source_documents.map((source,index)=><article className="person-row" key={`${source.title}-${index}`}><div className="person-avatar">📄</div><div className="person-copy"><strong>{source.title}</strong><span>{pageLabel(source.page_start,source.page_end)??'Référence du cours'}</span></div></article>)}</div></section>}
  {lesson.sources.length>0&&<details className="card lesson-reference-strip lesson-external-details"><summary><span className="eyebrow">↗ Références externes · {lesson.sources.length}</span></summary><div className="people-list">{lesson.sources.map((source,index)=>{if(typeof source==='string')return<article className="person-row" key={`${source}-${index}`}><div className="person-avatar">↗</div><div className="person-copy"><strong>{source}</strong><span>Source complémentaire</span></div></article>;const title=source.title||source.label||'Référence externe';return<article className="person-row" key={`${title}-${index}`}><div className="person-avatar">↗</div><div className="person-copy"><strong>{title}</strong><span>Source complémentaire</span></div>{source.url&&<a className="text-link" href={source.url} target="_blank" rel="noreferrer">Ouvrir</a>}</article>})}</div></details>}
  <section className="card centered"><p className="eyebrow">Passage à l’action</p><h2>Vérifie ce que tu as retenu</h2><p>{canQuiz?'Une courte série ciblée pour transformer la lecture en mémorisation active.':`Passe ton profil en K${lesson.year.number} lorsque cette année devient ton année active pour débloquer le quiz.`}</p><button className="primary-button wide" disabled={busy||lesson.question_count===0||!canQuiz} onClick={launchQuiz}>{busy?'Préparation…':!canQuiz?`Quiz disponible en K${lesson.year.number}`:lesson.question_count>0?`Lancer le quiz (${Math.min(10,lesson.question_count)} questions)`:'Quiz en attente de validation'}</button><Link className="secondary-button wide" to="/parcours">Retour au parcours</Link>{error&&<p className="feedback">{error}</p>}</section>
 </div>
}
