import { Link } from 'react-router-dom'

export default function PublicInfoPage(){
 return <div className="stack">
  <section className="hero-card"><div className="hero-copy"><p className="eyebrow light">Kineo</p><h1>Informations & assistance</h1><p>Les informations essentielles pour utiliser Kineo dans un cadre pédagogique clair et transparent.</p></div><div className="hero-orbit" aria-hidden="true"><span>ℹ️</span></div></section>
  <section className="card"><p className="eyebrow">Usage</p><h2>Plateforme pédagogique</h2><p>Kineo est une application de révision destinée aux étudiants des cursus de santé proposés dans l’application. Les cours, quiz, défis et outils de progression ont une finalité exclusivement pédagogique.</p><p><strong>Kineo n’est pas un dispositif médical.</strong> L’application ne fournit ni diagnostic, ni prescription, ni conseil médical personnalisé et ne remplace pas les enseignements officiels, les professionnels de santé ou les recommandations des autorités compétentes.</p></section>
  <section className="card"><p className="eyebrow">Confidentialité</p><h2>Données utilisées</h2><p>Kineo utilise les données nécessaires au fonctionnement du compte et à l’expérience d’apprentissage : identité de profil renseignée par l’utilisateur, adresse de connexion, cursus et niveau, progression, réponses aux exercices, statistiques, badges, relations entre amis, défis et éventuelle photo de profil.</p><p>Ces données servent au fonctionnement de l’application, à la personnalisation des révisions, au suivi de progression, aux fonctions sociales demandées par l’utilisateur, à la sécurité et à l’amélioration du service. Kineo n’a pas vocation à collecter des données médicales personnelles pour établir un diagnostic.</p><p>Une version juridique définitive de la politique de confidentialité précisera avant l’ouverture publique l’identité de l’éditeur, les coordonnées de contact, les durées de conservation, les sous-traitants, la base juridique des traitements et les modalités complètes d’exercice des droits.</p></section>
  <section className="card"><p className="eyebrow">Conditions d’utilisation</p><h2>Règles essentielles</h2><p>L’utilisateur doit fournir des informations de compte exactes, préserver la confidentialité de ses accès et utiliser Kineo dans un cadre légal et pédagogique. Les contenus ne doivent pas être utilisés comme substitut à une décision clinique ou médicale.</p><p>Les fonctionnalités, cursus et contenus peuvent évoluer afin d’améliorer leur qualité pédagogique. Les sources et validations disponibles dans Kineo restent la référence interne pour les contenus publiés.</p></section>
  <section className="card"><p className="eyebrow">Compte & droits</p><h2>Garder le contrôle de ses données</h2><p>La déconnexion ne supprime aucune donnée. Kineo ne supprime pas automatiquement un compte étudiant depuis cette page.</p><p>Avant le lancement public, une procédure d’assistance permettra à un utilisateur de demander l’accès, la rectification ou, lorsqu’il le souhaite et que la réglementation le permet, la suppression de son compte et de ses données. Toute suppression devra résulter d’une demande volontaire et vérifiée.</p></section>
  <section className="card"><p className="eyebrow">Assistance</p><h2>Besoin d’aide ?</h2><p>Le bouton de retour intégré à Kineo permet déjà de signaler un problème fonctionnel ou pédagogique. Une adresse de support officielle sera ajoutée ici avant l’ouverture au public.</p><div className="friend-actions"><Link className="secondary-button" to="/profil">Retour au profil</Link></div></section>
  <section className="card muted-card"><p><strong>Pré-lancement.</strong> Les mentions d’éditeur, coordonnées officielles, hébergement et informations juridiques définitives seront complétées avant l’ouverture publique. Aucune information n’est inventée dans cette version.</p></section>
 </div>
}
