import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { finishFriendChallenge } from '../services/challengeApi'
import { finishDailyChallengeV2, finishQuizSessionV2, getQuizQuestionsV4, startDailyChallengeV2, startSmartRevisionV2, submitQuizAnswerV3, type QuizQuestionV3 } from '../services/kineoApi'

type AnswerResult = { correct?: boolean; xp_earned?: number; correction?: { explanation?: string | null; correct_option_ids?: string[]; correct_answer?: string | null; correct_pairs?: Array<{ left:string; right:string }> } }
type ChallengeFinish = { score?:number; xp_earned?:number; bonus_xp?:number; current_streak?:number; new_badges_count?:number }
type SessionSummary = { score:number; correct:number; total:number; xp:number; streak?:number; badges?:number; daily:boolean; duel?:boolean }
const ACTIVE_SMART_SESSION='kineo_active_smart_session'

export default function RevisionPage(){
 const [searchParams]=useSearchParams(); const mode=searchParams.get('mode'); const externalSession=searchParams.get('session'); const challengeId=searchParams.get('challenge'); const isDaily=mode==='daily'; const isChallenge=mode==='challenge'&&Boolean(challengeId); const isLesson=mode==='lesson'&&Boolean(externalSession)
 const resumeChecked=useRef(false); const externalChecked=useRef(false)
 const [sessionId,setSessionId]=useState<string|null>(null); const [questions,setQuestions]=useState<QuizQuestionV3[]>([]); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<string|null>(null); const [textAnswer,setTextAnswer]=useState(''); const [matching,setMatching]=useState<Record<string,string>>({}); const [result,setResult]=useState<AnswerResult|null>(null); const [message,setMessage]=useState<string|null>(null); const [summary,setSummary]=useState<SessionSummary|null>(null); const [busy,setBusy]=useState(false); const [startedAt,setStartedAt]=useState(Date.now()); const [correctCount,setCorrectCount]=useState(0); const [sessionXp,setSessionXp]=useState(0)
 const current=questions[index]; const progress=useMemo(()=>questions.length?((index+1)/questions.length)*100:0,[index,questions.length]); const leftItems=(current?.metadata?.left_items??[]) as string[]; const rightItems=(current?.metadata?.right_items??[]) as string[]
 useEffect(()=>{if(!externalSession||externalChecked.current)return;externalChecked.current=true;setBusy(true);getQuizQuestionsV4(externalSession).then(async qs=>{if(!qs.length){await finishQuizSessionV2(externalSession);setMessage('Ce quiz est déjà terminé.');return}setSessionId(externalSession);setQuestions(qs);setIndex(0);setStartedAt(Date.now())}).catch((e:Error)=>setMessage(e.message)).finally(()=>setBusy(false))},[externalSession])
 useEffect(()=>{if(isDaily||externalSession||resumeChecked.current)return;resumeChecked.current=true;const saved=localStorage.getItem(ACTIVE_SMART_SESSION);if(!saved)return;setBusy(true);getQuizQuestionsV4(saved).then(async qs=>{if(!qs.length){await finishQuizSessionV2(saved);localStorage.removeItem(ACTIVE_SMART_SESSION);setMessage('Ta session précédente a été finalisée automatiquement.');return}setSessionId(saved);setQuestions(qs);setMessage('Session précédente reprise automatiquement.')}).catch(()=>localStorage.removeItem(ACTIVE_SMART_SESSION)).finally(()=>setBusy(false))},[externalSession,isDaily])
 const canValidate=useMemo(()=>{if(!current||result)return false;if(current.type==='mcq'||current.type==='true_false')return Boolean(selected);if(current.type==='fill_blank')return textAnswer.trim().length>0;if(current.type==='matching')return leftItems.length>0&&leftItems.every(left=>Boolean(matching[left]));return false},[current,leftItems,matching,result,selected,textAnswer])
 function resetAnswerState(){setSelected(null);setTextAnswer('');setMatching({});setResult(null);setMessage(null);setStartedAt(Date.now())}
 async function start(){if((isLesson||isChallenge)&&externalSession)return;setBusy(true);setMessage(null);setSummary(null);setCorrectCount(0);setSessionXp(0);try{if(isDaily){const daily=await startDailyChallengeV2();if(daily.completed){setSummary({score:daily.score??0,correct:0,total:daily.question_count,xp:daily.xp_earned??0,daily:true});return}const qs=await getQuizQuestionsV4(daily.session_id);setSessionId(daily.session_id);setQuestions(qs)}else{const session=await startSmartRevisionV2(10);localStorage.setItem(ACTIVE_SMART_SESSION,session);setSessionId(session);setQuestions(await getQuizQuestionsV4(session))}setIndex(0);resetAnswerState()}catch(e){setMessage(e instanceof Error?e.message:'Impossible de démarrer la session.')}finally{setBusy(false)}}
 function buildAnswer(){if(!current)return{};if(current.type==='mcq'||current.type==='true_false')return{option_id:selected};if(current.type==='fill_blank')return{text:textAnswer.trim()};if(current.type==='matching')return{pairs:leftItems.map(left=>({left,right:matching[left]}))};return{}}
 async function validate(){if(!sessionId||!current||!canValidate)return;setBusy(true);setMessage(null);try{const answer=await submitQuizAnswerV3({sessionId,questionId:current.id,answer:buildAnswer(),responseTimeMs:Date.now()-startedAt}) as AnswerResult;setResult(answer);if(answer.correct)setCorrectCount(v=>v+1);if(answer.xp_earned)setSessionXp(v=>v+(answer.xp_earned??0))}catch(e){setMessage(e instanceof Error?e.message:'Impossible de valider la réponse.')}finally{setBusy(false)}}
 async function next(){if(!sessionId)return;if(index+1>=questions.length){setBusy(true);try{const total=questions.length;const finalCorrect=correctCount;const finalScore=total?Math.round((finalCorrect/total)*100):0;let finalXp=sessionXp;let streak:number|undefined;let badges:number|undefined;if(isDaily){const done=await finishDailyChallengeV2(sessionId) as ChallengeFinish;finalXp=done.xp_earned??sessionXp;streak=done.current_streak;badges=done.new_badges_count}else{await finishQuizSessionV2(sessionId);if(!externalSession)localStorage.removeItem(ACTIVE_SMART_SESSION)}if(isChallenge&&challengeId)await finishFriendChallenge(challengeId,finalScore);setSummary({score:finalScore,correct:finalCorrect,total,xp:finalXp,streak,badges,daily:isDaily,duel:isChallenge});setQuestions([]);setSessionId(null);setResult(null)}catch(e){setMessage(e instanceof Error?e.message:'Impossible de terminer la session.')}finally{setBusy(false)}return}setIndex(v=>v+1);resetAnswerState()}
 function renderAnswerInput(){if(!current)return null;if(current.type==='mcq'||current.type==='true_false')return <div className="answers">{current.question_options.map(option=>{const ids=result?.correction?.correct_option_ids??[];const ok=Boolean(result&&ids.includes(option.id));const chosen=selected===option.id;const cls=['answer',chosen?'selected':'',ok?'correct':'',result&&chosen&&!ok?'incorrect':''].filter(Boolean).join(' ');return <button key={option.id} className={cls} onClick={()=>!result&&setSelected(option.id)} disabled={busy||Boolean(result)}>{option.option_text}</button>})}</div>;if(current.type==='fill_blank')return <div className="text-answer-wrap"><label>Ta réponse</label><input className="text-answer" value={textAnswer} onChange={e=>setTextAnswer(e.target.value)} disabled={busy||Boolean(result)}/>{result?.correction?.correct_answer&&<p>Réponse attendue : <strong>{result.correction.correct_answer}</strong></p>}</div>;if(current.type==='matching')return <div className="matching-grid">{leftItems.map(left=><label className="matching-row" key={left}><span>{left}</span><select value={matching[left]??''} onChange={e=>setMatching(v=>({...v,[left]:e.target.value}))} disabled={busy||Boolean(result)}><option value="">Choisir…</option>{rightItems.map(right=><option key={right}>{right}</option>)}</select></label>)}</div>;return <p>Ce format sera bientôt disponible.</p>}
 if(summary)return <div className="stack"><section className="session-complete"><div className="completion-icon">{summary.duel?'⚔️':summary.score>=80?'🏆':summary.score>=60?'🎉':'💪'}</div><p className="eyebrow">{summary.duel?'Défi terminé':'Session terminée'}</p><h1>{summary.duel?'Ton score est enregistré !':summary.score>=80?'Excellent travail !':summary.score>=60?'Belle progression !':'Continue, tu progresses !'}</h1><div className="completion-score">{summary.score}%</div><p>{summary.duel?'Le résultat final apparaîtra dès que ton ami aura joué.':`${summary.correct} bonne${summary.correct>1?'s':''} réponse${summary.correct>1?'s':''} sur ${summary.total}`}</p></section><section className="completion-grid"><article className="card"><span>⚡ XP gagnés</span><strong>+{summary.xp}</strong></article>{summary.streak!==undefined&&<article className="card"><span>🔥 Série</span><strong>{summary.streak} j</strong></article>}<article className="card"><span>🎯 Score</span><strong>{summary.score}%</strong></article></section>{Boolean(summary.badges)&&<section className="card badge-unlock"><span>🏅</span><div><strong>Nouveau badge débloqué !</strong><p>Va voir ta collection de récompenses.</p></div></section>}<div className="completion-actions"><Link className="primary-button" to={summary.duel?'/amis':'/'}>{summary.duel?'Voir mes défis':'Retour à l’accueil'}</Link>{!summary.duel&&<button className="secondary-button" onClick={()=>{setSummary(null);void start()}}>Rejouer</button>}<Link className="text-link" to="/rewards">Voir mes récompenses</Link></div></div>
 if(!current){const eyebrow=isDaily?'Challenge du jour':isChallenge?'Défi entre amis':isLesson?'Quiz de leçon':'Révision intelligente';const title=isDaily?'10 questions pour garder ta flamme 🔥':isChallenge?'Même quiz. Même règles. À toi de jouer ⚔️':isLesson?'Quiz ciblé sur cette leçon':'10 questions adaptées à ta progression';return <div className="stack"><section className="hero-card"><div className="hero-copy"><p className="eyebrow light">{eyebrow}</p><h1>{title}</h1><p>{isDaily?'Termine le challenge pour gagner le bonus quotidien.':isChallenge?'Ton score sera comparé à celui de ton ami.': 'Le moteur choisit les notions utiles à revoir maintenant.'}</p>{!isLesson&&!isChallenge&&<button className="primary-button hero-action" onClick={start} disabled={busy}>{busy?'Préparation…':isDaily?'Lancer le challenge':'Commencer'}</button>}</div><div className="hero-orbit">{isDaily?'🔥':isChallenge?'⚔️':isLesson?'🎯':'🧠'}</div></section>{message&&<section className="card centered"><p>{message}</p></section>}</div>}
 return <div className="stack"><section className="card"><div className="section-heading"><div><p className="eyebrow">{isDaily?'Challenge du jour':isChallenge?'Défi entre amis':isLesson?'Quiz de leçon':'Révision intelligente'}</p><h2>Question {index+1} sur {questions.length}</h2></div><strong>{Math.round(progress)}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div></section><section className="card quiz-card"><p className="eyebrow">{current.type==='mcq'?'QCM':current.type==='true_false'?'Vrai / Faux':current.type==='fill_blank'?'Texte à compléter':current.type==='matching'?'Association':'Question'}</p><h1>{current.question_text}</h1>{current.image_url&&<img className="question-image" src={current.image_url} alt="Illustration de la question"/>}{renderAnswerInput()}{!result?<button className="primary-button wide" onClick={validate} disabled={!canValidate||busy}>{busy?'Validation…':'Valider ma réponse'}</button>:<div className={result.correct?'result-box success':'result-box retry'}><strong>{result.correct?'Bonne réponse ✅':'À revoir 💡'}</strong>{typeof result.xp_earned==='number'&&result.xp_earned>0&&<span>+{result.xp_earned} XP</span>}{result.correction?.explanation&&<p>{result.correction.explanation}</p>}<button className="primary-button wide" onClick={next} disabled={busy}>{index+1>=questions.length?'Voir mes résultats':'Question suivante'}</button></div>}{message&&<p className="feedback">{message}</p>}</section></div>
}
