import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { getGamificationSummaryV2,getRecentRevisionSessionsV1,getUserStatsV2,type GamificationSummaryV2,type RevisionHistoryItem,type UserStatsV2 } from '../services/kineoApi'
import { getCurrentProfile } from '../services/profileApi'
import './StatisticsPage.css'
function durationLabel(seconds:number){const totalMin=Math.floor(seconds/60);const hours=Math.floor(totalMin/60);const min=totalMin%60;return hours>0?`${hours} h ${min.toString().padStart(2,'0')} min`:totalMin>0?`${totalMin} min`:`${seconds}s`}
export default function StatisticsPage(){
 const [stats,setStats]=useState<UserStatsV2|null>(null),[game,setGame]=useState<GamificationSummaryV2|null>(null),[history,setHistory]=useState<RevisionHistoryItem[]>([]),[studyYear,setStudyYear]=useState<number|null>(null),[days,setDays]=useState(30),[error,setError]=useState<string|null>(null)
 useEffect(()=>{let stop=false;Promise.all([getUserStatsV2(days),getRecentRevisionSessionsV1(12),getCurrentProfile(),getGamificationSummaryV2()]).then(([s,h,p,g])=>{if(!stop){setStats(s);setHistory(h);setStudyYear(p?.study_year??null);setGame(g)}}).catch((e:Error)=>!stop&&setError(e.message));return()=>{stop=true}},[days])
 const subjects=useMemo(()=>stats?.subjects.filter(x=>x.published_questions>0&&(!studyYear||x.year_number===studyYear))??[],[stats,studyYear]),activity=stats?.daily_activity??[],max=Math.max(1,...activity.map(x=>x.attempts)),revisionSeconds=history.reduce((n,x)=>n+x.duration_seconds,0)
 if(error)return <section className="card"><h1>Statistiques indisponibles</h1><p>{error}</p></section>;if(!stats)return <section className="card skeleton-card"><p>Calcul de ta progression…</p></section>
 const s=stats.summary
 return <div className="stack stats-mobile"><header className="stats-page-head"><div><h1>Mes statistiques</h1><p>Visualise tes progrès et reste motivé !</p></div><div className="stats-header-actions"><span className="profile-context">Kiné France · {studyYear?`K${studyYear}`:'Niveau profil'}</span><Link className="stats-badges-link" to="/rewards">◆ Mes badges</Link></div></header>
 <section className="stats-overview card"><div className="progress-ring" style={{'--progress':Math.min(100,s.mastery_percent)} as React.CSSProperties}><div><strong>{s.mastery_percent}%</strong><span>maîtrise</span></div></div><div className="overview-copy"><p className="eyebrow">Progression globale</p><h2>{s.mastered_questions} questions maîtrisées</h2><p>{s.attempted_questions} questions travaillées sur ton niveau actuel.</p><div className="progress-track"><div className="progress-fill" style={{width:Math.min(100,s.mastery_percent)+'%'}}/></div></div></section>
 <section className="stats-kpi-grid"><article className="card stat-kpi"><span>🔥</span><strong>{game?.streak.current??0}</strong><small>Jours de série</small></article><article className="card stat-kpi"><span>✦</span><strong>{s.xp_total}</strong><small>XP gagnés</small></article><article className="card stat-kpi"><span>✓</span><strong>{s.accuracy_percent}%</strong><small>Taux de réussite</small></article><article className="card stat-kpi"><span>⏱</span><strong>{durationLabel(revisionSeconds)}</strong><small>Temps de révision*</small></article><article className="card stat-kpi"><span>❓</span><strong>{s.attempts}</strong><small>Réponses</small></article><article className="card stat-kpi"><span>✓</span><strong>{s.correct_answers}</strong><small>Bonnes réponses</small></article></section>
 <section className="card"><div className="section-heading"><div><p className="eyebrow">Ma progression</p><h2>Évolution</h2></div><div className="period-tabs">{[[7,'7 jours'],[30,'30 jours'],[90,'3 mois']].map(([d,l])=><button key={d} className={days===d?'active':''} onClick={()=>setDays(Number(d))}>{l}</button>)}</div></div><div className="activity-chart">{activity.map(x=><div className="activity-day" key={x.date} title={`${x.date} · ${x.attempts} réponses · ${x.accuracy_percent}%`}><div className="activity-bar-wrap"><div className="activity-bar" style={{height:Math.max(8,Math.round(x.attempts/max*100))+'%'}}/></div><span>{new Date(x.date+'T12:00').toLocaleDateString('fr-FR',{weekday:'narrow'})}</span></div>)}</div></section>
 <section className="card"><div className="section-heading"><div><p className="eyebrow">Par matière</p><h2>Maîtrise des contenus {studyYear?`K${studyYear}`:''}</h2></div></div><div className="subject-list">{subjects.map(x=><article className="subject-progress" key={x.id}><div className="subject-row"><div><strong>{x.name}</strong><span>{x.attempted_questions}/{x.published_questions} questions vues · {x.accuracy_percent}% réussite</span></div><div className="subject-score"><strong>{x.mastery_percent}%</strong><span>maîtrise</span></div></div><div className="progress-track small"><div className="progress-fill" style={{width:Math.min(100,x.mastery_percent)+'%'}}/></div><Link className="text-link" to={`/revision-matiere?subjectId=${encodeURIComponent(x.id)}&subject=${encodeURIComponent(x.name)}`}>Réviser cette matière</Link></article>)}</div></section>
<p className="stats-footnote">* Temps calculé sur les dernières sessions disponibles.</p></div>
}