import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { getContentReviewQueue,setContentReviewStatus,setVisualApproval,type ReviewQuestion,type ReviewQueue } from '../services/adminApi'
import './AdminPage.css'
import './VisualAdminPage.css'

const typeLabel:Record<string,string>={hotspot:'Repérage anatomique',image:'Placement d’étiquettes'}

export default function VisualAdminPage(){
 const [queue,setQueue]=useState<ReviewQueue|null>(null)
 const [busy,setBusy]=useState<string|null>(null)
 const [error,setError]=useState<string|null>(null)
 async function load(){setError(null);try{setQueue(await getContentReviewQueue())}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les visuels.')}}
 useEffect(()=>{void load()},[])
 const visuals=useMemo(()=>queue?.questions.filter(q=>q.type==='hotspot'||q.type==='image')??[],[queue])
 async function approve(item:ReviewQuestion,approved:boolean){setBusy(item.id);setError(null);try{await setVisualApproval(item.id,approved);await load()}catch(e){setError(e instanceof Error?e.message:'Impossible de modifier la validation visuelle.')}finally{setBusy(null)}}
 async function changeStatus(item:ReviewQuestion,status:'review'|'validated'|'published'){setBusy(item.id);setError(null);try{await setContentReviewStatus(item.id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Impossible de modifier le statut.')}finally{setBusy(null)}}
 if(!queue&&!error)return <section className="card"><p>Chargement des exercices visuels…</p></section>
 if(error&&!queue)return <section className="card"><p className="eyebrow">Administration</p><h1>Validation visuelle indisponible</h1><p>{error}</p><Link className="secondary-button" to="/admin">Retour à l’administration</Link></section>
 return <div className="stack admin-stack">
  <section className="hero-card"><div className="hero-copy"><span className="hero-kicker">Administration · Visuels</span><h1>Contrôle anatomique</h1><p>Vérifie le schéma et la position attendue avant d’autoriser une question visuelle à passer en validation pédagogique.</p><Link className="text-link" to="/admin">← Centre admin</Link></div><div className="hero-orbit"><span>🦴</span></div></section>
  <section className="card"><div className="section-heading"><div><p className="eyebrow">File visuelle</p><h2>{visuals.length} exercice{visuals.length>1?'s':''} à suivre</h2></div><span className="admin-alert">{visuals.filter(v=>!v.visual_approved).length} non approuvé{visuals.filter(v=>!v.visual_approved).length>1?'s':''}</span></div>{error&&<p className="feedback-error">{error}</p>}<div className="visual-admin-list">{visuals.length===0?<div className="admin-empty"><span>✓</span><strong>Aucun visuel en attente.</strong></div>:visuals.map(item=><article className="review-item visual-review-card" key={item.id}><div className="review-head"><div><span className="review-type">{typeLabel[item.type]??item.type}</span><strong>K{item.year_number} · {item.subject_name}</strong></div><span className={item.visual_approved?'admin-ok':'admin-alert'}>{item.visual_approved?'Visuel approuvé':'À contrôler'}</span></div><h3>{item.question_text}</h3><p className="review-path">{item.chapter_name} · {item.lesson_title}</p>{item.image_url?<div className="visual-review-image"><img src={item.image_url} alt="Schéma anatomique à valider"/>{item.type==='hotspot'&&item.hotspot&&<span className="visual-review-zone" style={{left:`${item.hotspot.x}%`,top:`${item.hotspot.y}%`,width:`${Number(item.hotspot.radius??8)*2}%`,aspectRatio:'1'}} title={item.hotspot.label??'Zone attendue'}/>} {item.type==='image'&&(item.label_targets??[]).map((target,index)=><span className="visual-review-label" key={target.key??index} style={{left:`${target.x}%`,top:`${target.y}%`}}>{index+1}</span>)}</div>:<p className="feedback-error">Image absente.</p>}{item.type==='image'&&Boolean(item.label_targets?.length)&&<div className="visual-review-targets">{item.label_targets?.map((target,index)=><span key={target.key??index}><strong>{index+1}</strong> {target.label??target.key??'Étiquette'}</span>)}</div>}<div className="review-source"><strong>📚 {item.source_title??'Source absente'}</strong><span>{item.source_page?`Page ${item.source_page}`:'Page non renseignée'}</span>{item.source_excerpt&&<blockquote>{item.source_excerpt}</blockquote>}</div><div className="admin-feedback-actions"><span>Statut : {item.validation_status}</span>{!item.visual_approved?<button className="secondary-button compact-button" disabled={busy===item.id||!item.image_url} onClick={()=>void approve(item,true)}>Approuver le visuel</button>:<button className="text-link" disabled={busy===item.id} onClick={()=>void approve(item,false)}>Retirer l’approbation</button>}{item.visual_approved&&item.validation_status==='review'&&<button className="secondary-button compact-button" disabled={busy===item.id} onClick={()=>void changeStatus(item,'validated')}>Valider la question</button>}{item.visual_approved&&item.validation_status==='validated'&&<button className="primary-button compact-button" disabled={busy===item.id} onClick={()=>void changeStatus(item,'published')}>Publier</button>}</div></article>)}</div></section>
 </div>
}
