import { NavLink, Route, Routes } from 'react-router-dom'
import AdminGate from './auth/AdminGate'
import AuthGate from './auth/AuthGate'
import RevisionContentGate from './auth/RevisionContentGate'
import ExamTimerBar from './components/ExamTimerBar'
import FeedbackButton from './components/FeedbackButton'
import HeaderProfileButton from './components/HeaderProfileButton'
import NotificationBell from './components/NotificationBell'
import AdminPage from './pages/AdminPage'
import CurriculumPage from './pages/CurriculumPage'
import DashboardPage from './pages/DashboardPage'
import FriendsPage from './pages/FriendsPage'
import GamificationPage from './pages/GamificationPage'
import LeaderboardPage from './pages/LeaderboardPage'
import LessonPage from './pages/LessonPage'
import LibraryPage from './pages/LibraryPage'
import MockExamPage from './pages/MockExamPage'
import NotFoundPage from './pages/NotFoundPage'
import NotificationsPage from './pages/NotificationsPage'
import ProfilePage from './pages/ProfilePage'
import RevisionPage from './pages/RevisionPage'
import SessionReviewPage from './pages/SessionReviewPage'
import StatisticsPage from './pages/StatisticsPage'
import SubjectRevisionPage from './pages/SubjectRevisionPage'
import VisualRevisionPage from './pages/VisualRevisionPage'
import WeakRevisionPage from './pages/WeakRevisionPage'

const navItems=[{to:'/',label:'Accueil',icon:'⌂',end:true},{to:'/parcours',label:'Parcours',icon:'▦'},{to:'/revision',label:'Réviser',icon:'✦'},{to:'/stats',label:'Stats',icon:'↗'},{to:'/rewards',label:'Badges',icon:'★'}]
export default function App(){return <AuthGate><div className="app-shell"><header className="topbar"><div className="brand-lockup"><span className="brand-mark">K</span><div><strong className="brand">Kineo</strong><span className="tagline">Réviser. Progresser. Retenir.</span></div></div><div className="topbar-actions"><NotificationBell/><HeaderProfileButton/></div></header><ExamTimerBar/><main className="content"><Routes><Route path="/" element={<DashboardPage/>}/><Route path="/parcours" element={<CurriculumPage/>}/><Route path="/lesson/:lessonId" element={<LessonPage/>}/><Route path="/bibliotheque" element={<LibraryPage/>}/><Route path="/revision" element={<RevisionContentGate><RevisionPage/></RevisionContentGate>}/><Route path="/revision-matiere" element={<SubjectRevisionPage/>}/><Route path="/session/:sessionId" element={<SessionReviewPage/>}/><Route path="/anatomie" element={<VisualRevisionPage/>}/><Route path="/mes-erreurs" element={<WeakRevisionPage/>}/><Route path="/examen" element={<MockExamPage/>}/><Route path="/stats" element={<StatisticsPage/>}/><Route path="/rewards" element={<GamificationPage/>}/><Route path="/classement" element={<LeaderboardPage/>}/><Route path="/profil" element={<ProfilePage/>}/><Route path="/amis" element={<FriendsPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="/admin" element={<AdminGate><AdminPage/></AdminGate>}/><Route path="*" element={<NotFoundPage/>}/></Routes></main><FeedbackButton/><nav className="bottom-nav" aria-label="Navigation principale">{navItems.map(item=><NavLink key={item.to} to={item.to} end={item.end}><span className="nav-icon" aria-hidden="true">{item.icon}</span><span>{item.label}</span></NavLink>)}</nav></div></AuthGate>}
