import { NavLink, Route, Routes } from 'react-router-dom'
import AdminGate from './auth/AdminGate'
import AuthGate from './auth/AuthGate'
import RevisionContentGate from './auth/RevisionContentGate'
import RevisionModeGate from './auth/RevisionModeGate'
import AppVersionBadge from './components/AppVersionBadge'
import ExamTimerBar from './components/ExamTimerBar'
import FeedbackButton from './components/FeedbackButton'
import HeaderProfileButton from './components/HeaderProfileButton'
import NotificationBell from './components/NotificationBell'
import OfflineStatus from './components/OfflineStatus'
import ProgramSwitcher from './components/ProgramSwitcher'
import { getCurrentProgram } from './curriculum/programs'
import AdminPage from './pages/AdminPage'
import CurriculumPage from './pages/CurriculumPage'
import DashboardPage from './pages/DashboardPage'
import FriendsPage from './pages/FriendsPage'
import GamificationPage from './pages/GamificationPage'
import LeaderboardPage from './pages/LeaderboardPage'
import LessonPage from './pages/LessonPage'
import LibraryPage from './pages/LibraryPage'
import MockExamPage from './pages/MockExamPage'
import NotFoundPage from './pages/NotFoundPage'
import NotificationsPage from './pages/NotificationsPage'
import ProfilePage from './pages/ProfilePage'
import ProgramLandingPage from './pages/ProgramLandingPage'
import ProgramsPage from './pages/ProgramsPage'
import RevisionPage from './pages/RevisionPage'
import './pages/RevisionPage.css'
import SessionReviewPage from './pages/SessionReviewPage'
import StatisticsPage from './pages/StatisticsPage'
import SubjectRevisionPage from './pages/SubjectRevisionPage'
import VisualAdminPage from './pages/VisualAdminPage'
import VisualRevisionPage from './pages/VisualRevisionPage'
import WeakRevisionPage from './pages/WeakRevisionPage'
import './curriculum.css'

export default function App(){
 const program=getCurrentProgram(),isKineoFrance=program.id==='kineo-fr'
 const navItems=isKineoFrance?[{to:'/',label:'Accueil',icon:'⌂',end:true},{to:'/parcours',label:'Parcours',icon:'▦'},{to:'/revision',label:'Réviser',icon:'✦'},{to:'/stats',label:'Stats',icon:'↗'},{to:'/rewards',label:'Badges',icon:'★'}]:[{to:'/',label:'Accueil',icon:'⌂',end:true},{to:'/programmes',label:'Cursus',icon:'▦'},{to:'/profil',label:'Profil',icon:'●'}]
 return <AuthGate><div className="app-shell"><OfflineStatus/><header className="topbar"><div className="brand-lockup"><span className="brand-mark">{program.accent}</span><div><strong className="brand">{program.shortName}</strong><span className="tagline">{isKineoFrance?'Réviser. Progresser. Retenir.':program.subtitle}</span><span className="brand-platform">Plateforme santé · nom définitif à venir</span></div><AppVersionBadge/></div><div className="topbar-actions"><ProgramSwitcher/><NotificationBell/><HeaderProfileButton/></div></header><ExamTimerBar/><main className="content"><Routes><Route path="/" element={isKineoFrance?<DashboardPage/>:<ProgramLandingPage/>}/><Route path="/programmes" element={<ProgramsPage/>}/><Route path="/parcours" element={isKineoFrance?<CurriculumPage/>:<ProgramLandingPage/>}/><Route path="/lesson/:lessonId" element={<LessonPage/>}/><Route path="/bibliotheque" element={<LibraryPage/>}/><Route path="/revision" element={<RevisionContentGate><RevisionPage/></RevisionContentGate>}/><Route path="/revision-matiere" element={<SubjectRevisionPage/>}/><Route path="/session/:sessionId" element={<SessionReviewPage/>}/><Route path="/anatomie" element={<RevisionModeGate mode="visual"><VisualRevisionPage/></RevisionModeGate>}/><Route path="/mes-erreurs" element={<RevisionModeGate mode="weak"><WeakRevisionPage/></RevisionModeGate>}/><Route path="/examen" element={<RevisionModeGate mode="exam"><MockExamPage/></RevisionModeGate>}/><Route path="/stats" element={<StatisticsPage/>}/><Route path="/rewards" element={<GamificationPage/>}/><Route path="/classement" element={<LeaderboardPage/>}/><Route path="/profil" element={<ProfilePage/>}/><Route path="/amis" element={<FriendsPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="/admin" element={<AdminGate><AdminPage/></AdminGate>}/><Route path="/admin/visuels" element={<AdminGate><VisualAdminPage/></AdminGate>}/><Route path="*" element={<NotFoundPage/>}/></Routes></main><FeedbackButton/><nav className="bottom-nav" aria-label="Navigation principale">{navItems.map(item=><NavLink key={item.to} to={item.to} end={item.end}><span className="nav-icon" aria-hidden="true">{item.icon}</span><span>{item.label}</span></NavLink>)}</nav></div></AuthGate>}
