-- IFSI minimum-10 completion batch 6
-- SAED, pain assessment, standard precautions, clinical English

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,image_url,metadata)
values
('12000001-71a0-4d01-9015-000000000001'::uuid,'b697e550-3445-427e-8166-16f524d1bbc5'::uuid,'Cas clinique — Lors d’une transmission urgente, pourquoi le format SAED réduit-il le risque de perte d’information ?','Le SAED impose une structure commune : situation actuelle, antécédents utiles, évaluation et demande explicite. Cette organisation facilite une transmission concise et complète.','[{"text":"Parce qu’il structure les informations essentielles dans un ordre commun","correct":true},{"text":"Parce qu’il remplace toute observation clinique","correct":false},{"text":"Parce qu’il supprime la nécessité de formuler une demande","correct":false},{"text":"Parce qu’il évite toute communication orale","correct":false}]'::jsonb,4,'HAS — SAED : guide de communication entre professionnels de santé',10,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.has-sante.fr/jcms/c_1776178/fr/saed-un-guide-pour-faciliter-la-communication-entre-professionnels-de-sante","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb),
('12000002-71a0-4d01-9015-000000000001'::uuid,'eaf874a8-ad30-414a-97a3-4e210cefaac3'::uuid,'Pourquoi faut-il tracer l’outil utilisé pour évaluer la douleur ?','La traçabilité de l’outil et du résultat permet de suivre l’évolution, de comparer les mesures et d’assurer la continuité des soins.','[{"text":"Pour rendre les réévaluations comparables et assurer la continuité des soins","correct":true},{"text":"Uniquement pour satisfaire une formalité administrative","correct":false},{"text":"Pour éviter toute réévaluation ultérieure","correct":false},{"text":"Pour remplacer l’observation clinique","correct":false}]'::jsonb,3,'HAS — Évaluation et réévaluation de la douleur',9,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.has-sante.fr/upload/docs/application/pdf/2018-03/guide_des_problemes_somatiques.pdf","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb),
('12000002-71a0-4d01-9015-000000000002'::uuid,'eaf874a8-ad30-414a-97a3-4e210cefaac3'::uuid,'Cas clinique — Après un antalgique, le score de douleur reste identique et l’impact fonctionnel persiste. Quelle conduite est la plus adaptée ?','Une absence d’amélioration après intervention impose une nouvelle analyse de la situation et une adaptation de la prise en charge.','[{"text":"Réévaluer la situation et adapter la prise en charge","correct":true},{"text":"Considérer le traitement comme efficace malgré l’absence d’amélioration","correct":false},{"text":"Ne plus mesurer la douleur","correct":false},{"text":"Changer d’échelle uniquement pour obtenir un score différent","correct":false}]'::jsonb,4,'HAS — Évaluation et réévaluation de la douleur',10,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.has-sante.fr/upload/docs/application/pdf/2018-03/guide_des_problemes_somatiques.pdf","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb),
('12000003-71a0-4d01-9015-000000000001'::uuid,'3c182f2f-6200-45a9-8a87-a15434c92bca'::uuid,'Quand faut-il porter des gants dans le cadre des précautions standard ?','Les gants sont indiqués lorsqu’un contact avec du sang, un liquide biologique, une muqueuse ou une peau lésée est possible.','[{"text":"Lorsqu’il existe un risque de contact avec sang, liquides biologiques, muqueuse ou peau lésée","correct":true},{"text":"Pour tout contact avec un patient sans exception","correct":false},{"text":"Uniquement lorsque les mains sont visiblement sales","correct":false},{"text":"Seulement après le soin","correct":false}]'::jsonb,3,'SF2H — Actualisation des précautions standard',9,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.sf2h.net/publications/actualisation-des-precautions-standard.html","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb),
('12000003-71a0-4d01-9015-000000000002'::uuid,'3c182f2f-6200-45a9-8a87-a15434c92bca'::uuid,'Cas clinique — Un soin expose à un risque de projection au visage. Quelle adaptation est attendue ?','Les précautions standard prévoient d’adapter les équipements de protection individuelle au risque de projection ou d’exposition.','[{"text":"Ajouter les protections adaptées au risque, notamment masque et protection oculaire","correct":true},{"text":"Retirer les gants pour mieux voir","correct":false},{"text":"Ne rien changer car les précautions standard sont identiques dans toutes les situations","correct":false},{"text":"Reporter uniquement le nettoyage après le soin","correct":false}]'::jsonb,4,'Ministère de la Santé — Précautions standard',10,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://sante.gouv.fr/IMG/pdf/Precautions_standard-web.pdf","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb),
('12000004-71a0-4d01-9015-000000000001'::uuid,'eaac3d4f-c9ff-44aa-a4f2-e8143a394354'::uuid,'What does “shortness of breath” mean in French clinical language?','“Shortness of breath” means essoufflement or difficulté à respirer selon le contexte.','[{"text":"Essoufflement / difficulté à respirer","correct":true},{"text":"Douleur abdominale","correct":false},{"text":"Nausée","correct":false},{"text":"Vertiges","correct":false}]'::jsonb,2,'NHS — Shortness of breath',9,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.nhs.uk/conditions/shortness-of-breath/","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb),
('12000004-71a0-4d01-9015-000000000002'::uuid,'eaac3d4f-c9ff-44aa-a4f2-e8143a394354'::uuid,'A patient says: “I feel dizzy and nauseous.” What is the best French translation?','“Dizzy” correspond à étourdi/vertigineux selon le contexte et “nauseous” signifie nauséeux.','[{"text":"Je me sens étourdi/vertigineux et nauséeux","correct":true},{"text":"J’ai mal à la poitrine et je suis essoufflé","correct":false},{"text":"J’ai faim et soif","correct":false},{"text":"J’ai une douleur lombaire","correct":false}]'::jsonb,3,'NHS — Feeling sick (nausea) / clinical symptom vocabulary',10,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.nhs.uk/symptoms/feeling-sick-nausea/","minimum_10_batch":"v6","source_validation":"institutional_validated"}'::jsonb)
on conflict(id) do nothing;

select public.refresh_release_health_status_v1();
