-- Progressive quiz enrichment batch 7
-- ES1 advanced application: knee, quadriceps, physical capacities, movement instructions, gait/hip

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,metadata)
values
('bbbbbbb1-71a0-4d01-9007-000000000001','56137876-979c-4931-a14d-48bac26e83de',
'Un paciente tiene dolor de rodilla al levantarse y sensación de inestabilidad al caminar. ¿Qué observación básica es más útil?',
'En una valoración inicial conviene relacionar apoyo, rango de movimiento, dolor y calidad de tareas funcionales, comparando ambos lados cuando sea pertinente.',
'[{"text":"Observar apoyo, movilidad, dolor y calidad funcional","correct":true},{"text":"Valorar solo el dolor en reposo","correct":false},{"text":"Ignorar la marcha","correct":false},{"text":"Concluir un diagnóstico por un único síntoma","correct":false}]'::jsonb,
4,'MedlinePlus — La estructura de una articulación',991,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000002','56137876-979c-4931-a14d-48bac26e83de',
'Caso de integración básica — La movilidad de rodilla parece conservada, pero el paciente necesita apoyo para levantarse. ¿Qué debe concluirse?',
'La anatomía y el rango deben interpretarse en relación con la función. Una movilidad aparentemente conservada no excluye una limitación funcional.',
'[{"text":"Hay que explorar la función además del rango articular","correct":true},{"text":"La rodilla funciona normal porque se mueve bien","correct":false},{"text":"El apoyo necesario no es relevante","correct":false},{"text":"No hace falta observar la tarea de levantarse","correct":false}]'::jsonb,
5,'MedlinePlus — La estructura de una articulación',992,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000003','e578fce9-30c2-4bf0-bf23-b0169bcc6a69',
'Durante una semi-sentadilla, un paciente completa las repeticiones pero pierde alineación de rodilla y control del tronco. ¿Qué dato debe pesar más?',
'La calidad del movimiento, la alineación, el control y la fatiga son relevantes; contar repeticiones no basta.',
'[{"text":"La calidad del gesto y el control","correct":true},{"text":"Solo el número de repeticiones","correct":false},{"text":"Únicamente la velocidad","correct":false},{"text":"Ignorar la alineación si termina la serie","correct":false}]'::jsonb,
4,'MedlinePlus — Ejercicios para ayudar a prevenir caídas',991,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000004','e578fce9-30c2-4bf0-bf23-b0169bcc6a69',
'Caso de integración básica — Un paciente se levanta bien de la silla, pero controla mal el descenso al sentarse. ¿Qué lectura es la más adecuada?',
'El cuádriceps participa tanto en producir extensión como en controlar el movimiento durante tareas de apoyo. La bajada también aporta información funcional.',
'[{"text":"Debe valorarse también el control durante el descenso","correct":true},{"text":"La tarea es normal porque puede levantarse","correct":false},{"text":"El descenso no informa sobre función","correct":false},{"text":"Solo importa la fuerza máxima","correct":false}]'::jsonb,
5,'MedlinePlus — Ejercicios para ayudar a prevenir caídas',992,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000005','6bcac4ad-e3d1-41dd-92e3-101503b7e186',
'Si el objetivo principal es mejorar el equilibrio, ¿qué cambio aumenta de forma más directa esa demanda?',
'Reducir apoyos o aumentar la inestabilidad de la tarea incrementa la demanda de equilibrio, mientras que otras variables pueden dirigirse más a fuerza o resistencia.',
'[{"text":"Reducir progresivamente los apoyos","correct":true},{"text":"Aumentar solo el peso externo","correct":false},{"text":"Añadir únicamente más tiempo aeróbico","correct":false},{"text":"Mantener siempre la misma dificultad","correct":false}]'::jsonb,
4,'UVic-UCC — Bases de la Pràctica en Fisioteràpia',991,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000006','6bcac4ad-e3d1-41dd-92e3-101503b7e186',
'Caso de integración básica — Una tarea trabaja a la vez fuerza y equilibrio, pero el objetivo prioritario es la estabilidad. ¿Cómo debe progresarse?',
'Cuando una tarea combina capacidades, la progresión debe seguir siendo coherente con el objetivo principal.',
'[{"text":"Modificar la tarea para aumentar la demanda de estabilidad sin perder seguridad","correct":true},{"text":"Aumentar cualquier variable sin relación con el objetivo","correct":false},{"text":"Cambiar el objetivo durante la sesión sin motivo","correct":false},{"text":"Valorar solo la fatiga muscular","correct":false}]'::jsonb,
5,'UVic-UCC — Bases de la Pràctica en Fisioteràpia',992,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000007','7bc4bd2d-601d-460a-aa4e-73839eec1eb9',
'Un paciente no comprende una consigna de movimiento. ¿Cuál es la mejor estrategia inmediata?',
'Una buena consigna es breve y observable. Si no se comprende, puede reformularse, demostrarse o apoyarse en una referencia externa.',
'[{"text":"Reformular o demostrar la tarea de forma simple","correct":true},{"text":"Repetir exactamente la misma frase más rápido","correct":false},{"text":"Añadir varias instrucciones al mismo tiempo","correct":false},{"text":"Ignorar la ejecución incorrecta","correct":false}]'::jsonb,
4,'MedlinePlus — Rutina de ejercicios en interiores',991,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000008','7bc4bd2d-601d-460a-aa4e-73839eec1eb9',
'Caso de integración básica — Durante un ejercicio aparece mareo y falta de aire inusual. ¿Cuál debe ser la prioridad comunicativa?',
'Las consignas de seguridad incluyen detenerse ante síntomas importantes y pedir ayuda cuando sea necesario.',
'[{"text":"Pedir que se detenga y comunicar la necesidad de valoración","correct":true},{"text":"Animarle a terminar todas las repeticiones","correct":false},{"text":"Hablar solo de la técnica del ejercicio","correct":false},{"text":"Ignorar los síntomas si la postura es correcta","correct":false}]'::jsonb,
5,'MedlinePlus — Rutina de ejercicios en interiores',992,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000009','b21dd0d3-b05f-4a43-bbcf-4120bef3e97a',
'Un paciente presenta cojera y dolor inguinal al caminar. ¿Cuál es la actitud más adecuada en ES1?',
'En primer curso, el objetivo es integrar anatomía, función e historia sin diagnosticar por un único signo.',
'[{"text":"Describir marcha, apoyo, dolor y movilidad antes de interpretar","correct":true},{"text":"Diagnosticar una lesión de cadera solo por el dolor inguinal","correct":false},{"text":"Ignorar la columna y otras posibles fuentes de dolor","correct":false},{"text":"Valorar únicamente la longitud del paso","correct":false}]'::jsonb,
4,'UVic-UCC — Anatomia II / MedlinePlus — Problemas para caminar',991,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('bbbbbbb1-71a0-4d01-9007-000000000010','b21dd0d3-b05f-4a43-bbcf-4120bef3e97a',
'Caso de integración básica — La movilidad de cadera está limitada y el paciente compensa con el tronco durante la marcha. ¿Qué debe registrarse?',
'Una valoración funcional útil describe la limitación y las compensaciones observables, relacionándolas con la tarea sin concluir una causa aislada.',
'[{"text":"La limitación de cadera y la compensación del tronco durante la marcha","correct":true},{"text":"Solo el dolor declarado","correct":false},{"text":"Únicamente la amplitud pasiva","correct":false},{"text":"Un diagnóstico definitivo basado en la compensación","correct":false}]'::jsonb,
5,'UVic-UCC — Anatomia II / MedlinePlus — Problemas para caminar',992,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v7","difficulty_scale_version":"2026-10-v1"}'::jsonb)
on conflict(id) do nothing;

select public.refresh_release_health_status_v1();
