-- Progressive quiz enrichment batch 4
-- ES3/ES4 + IFSI S5 advanced reasoning

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,metadata)
values
('88888888-71a0-4d01-9004-000000000001','2ae99a08-b31f-478c-8e01-cd32c7c82556',
'Un paciente presenta dolor de rodilla, dificultad para subir escaleras y evita salir de casa. ¿Qué enfoque refleja mejor el uso de la CIF?',
'La CIF permite organizar déficits, limitaciones de actividad, participación y factores contextuales, en lugar de reducir el caso al síntoma corporal.',
'[{"text":"Relacionar dolor, actividad, participación y contexto","correct":true},{"text":"Describir únicamente el dolor","correct":false},{"text":"Ignorar las actividades de la vida diaria","correct":false},{"text":"Sustituir la valoración funcional por el diagnóstico médico","correct":false}]'::jsonb,
3,'UVic · Prácticum II · 2026-2027',951,'source_validated',true,'mcq','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000002','2ae99a08-b31f-478c-8e01-cd32c7c82556',
'Caso clínico — Tras varias sesiones mejora la fuerza, pero el paciente sigue sin recuperar la actividad funcional prioritaria. ¿Qué debe hacerse?',
'La evolución debe documentarse mediante reevaluación y comparación con los objetivos iniciales. Una mejora aislada no basta si el objetivo funcional no progresa.',
'[{"text":"Reevaluar función y objetivos antes de ajustar el tratamiento","correct":true},{"text":"Mantener el plan sin cambios porque aumentó la fuerza","correct":false},{"text":"Eliminar la valoración funcional","correct":false},{"text":"Concluir que el tratamiento ya es eficaz","correct":false}]'::jsonb,
4,'UVic · Prácticum II · 2026-2027',952,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000003','2ae99a08-b31f-478c-8e01-cd32c7c82556',
'Caso de integración — La reevaluación muestra menos dolor, mayor movilidad y mejor participación social, pero aparece una nueva barrera ambiental. ¿Qué decisión es más coherente?',
'El razonamiento debe integrar los cambios en funcionamiento y contexto. Una nueva barrera contextual puede justificar modificar objetivos o intervención aunque otros indicadores mejoren.',
'[{"text":"Integrar la nueva barrera en el diagnóstico funcional y ajustar el plan","correct":true},{"text":"Ignorarla porque el dolor ha mejorado","correct":false},{"text":"Mantener el diagnóstico funcional inicial sin reevaluación","correct":false},{"text":"Valorar únicamente la movilidad articular","correct":false}]'::jsonb,
5,'UVic · Prácticum II · 2026-2027',953,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000004','6bc7915b-da00-4f65-8692-fece6d1bb755',
'Caso clínico — Un estudiante se enfrenta a una situación que supera claramente su nivel de competencia. ¿Cuál es la conducta profesional más adecuada?',
'La responsabilidad profesional incluye reconocer límites y solicitar apoyo antes de actuar con una autonomía que todavía no está justificada.',
'[{"text":"Reconocer el límite y pedir supervisión","correct":true},{"text":"Actuar solo para demostrar autonomía","correct":false},{"text":"Ocultar la duda al equipo","correct":false},{"text":"Improvisar una intervención sin consultar","correct":false}]'::jsonb,
4,'UVic · Prácticum V · 2026-2027',951,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000005','6bc7915b-da00-4f65-8692-fece6d1bb755',
'Caso de integración — Un paciente presenta una limitación física moderada, pero su principal dificultad para participar es social y ambiental. ¿Cómo debe orientarse la atención?',
'La atención holística considera a la persona más allá del déficit físico e integra contexto social, comunicación, funcionalidad y coordinación.',
'[{"text":"Integrar los factores sociales y ambientales en el plan funcional","correct":true},{"text":"Tratar solo el déficit físico","correct":false},{"text":"Excluir la participación del análisis","correct":false},{"text":"Evitar la coordinación con otros profesionales","correct":false}]'::jsonb,
5,'UVic · Prácticum V · 2026-2027',952,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000006','f9a03454-930d-4da2-bcb8-384f8c501fd7',
'Durante la defensa del TFG, el tribunal pregunta por una limitación metodológica importante. ¿Cuál es la mejor respuesta?',
'Una defensa rigurosa debe explicar decisiones, reconocer límites y justificar cómo afectan a la interpretación de los resultados.',
'[{"text":"Reconocer la limitación y explicar su impacto","correct":true},{"text":"Negar cualquier limitación","correct":false},{"text":"Repetir literalmente la memoria escrita","correct":false},{"text":"Cambiar de tema sin responder","correct":false}]'::jsonb,
4,'UVic · Trabajo de Fin de Grado · 2026-2027',951,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000007','f9a03454-930d-4da2-bcb8-384f8c501fd7',
'Caso de integración — La pregunta del TFG, el método y los resultados son correctos por separado, pero las conclusiones responden a otra cuestión. ¿Cuál es el problema principal?',
'La calidad del TFG exige coherencia entre pregunta, método, resultados y conclusiones. Si les conclusions ne répondent pas à la question, la chaîne logique est rompue.',
'[{"text":"Falta coherencia interna entre pregunta y conclusiones","correct":true},{"text":"Falta únicamente diseño visual","correct":false},{"text":"La defensa oral sustituye esa incoherencia","correct":false},{"text":"No existe ningún problema si los resultados son correctos","correct":false}]'::jsonb,
5,'UVic · Trabajo de Fin de Grado · 2026-2027',952,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000008','a41836ca-60e0-445e-abe4-5a61fdf5ab98',
'Quel enchaînement décrit le mieux la progression générale évoquée dans la cancérogenèse ?',
'Le cours relie transformation cellulaire, mutations, dérégulation par oncogènes ou gènes suppresseurs, puis acquisition de caractéristiques tumorales pouvant aller jusqu’à l’invasion et aux métastases.',
'[{"text":"Altérations cellulaires → caractéristiques tumorales → invasion possible","correct":true},{"text":"Métastases → cellule normale → mutation","correct":false},{"text":"Angiogenèse → disparition de toute mutation","correct":false},{"text":"Invasion → retour spontané à une cellule normale","correct":false}]'::jsonb,
3,'Support IFSI fourni · Cancérogenèse',951,'source_validated',true,'mcq','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000009','a41836ca-60e0-445e-abe4-5a61fdf5ab98',
'Cas d’application — Une tumeur acquiert la capacité de développer de nouveaux vaisseaux et d’envahir les tissus voisins. Quels concepts du cours sont directement mobilisés ?',
'Le support associe à la progression tumorale l’angiogenèse et l’invasion, qui participent à l’évolution du processus cancéreux.',
'[{"text":"Angiogenèse et invasion","correct":true},{"text":"Uniquement hématopoïèse et coagulation","correct":false},{"text":"Uniquement cicatrisation physiologique","correct":false},{"text":"Absence de toute caractéristique tumorale","correct":false}]'::jsonb,
4,'Support IFSI fourni · Cancérogenèse',952,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('88888888-71a0-4d01-9004-000000000010','a41836ca-60e0-445e-abe4-5a61fdf5ab98',
'Cas d’intégration — Une cellule tumorale présente plusieurs altérations génétiques puis acquiert une capacité d’invasion à distance. Quelle lecture est la plus cohérente avec le cours ?',
'La cancérogenèse est un processus progressif associant altérations cellulaires et génétiques, acquisition de propriétés tumorales, invasion et possibilité de métastases.',
'[{"text":"Il s’agit d’une progression de la cancérogenèse vers l’invasion et les métastases","correct":true},{"text":"Les mutations excluent toute progression tumorale","correct":false},{"text":"L’invasion signifie nécessairement retour à un tissu normal","correct":false},{"text":"La présence de métastases est indépendante de toute évolution tumorale","correct":false}]'::jsonb,
5,'Support IFSI fourni · Cancérogenèse',953,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v4","difficulty_scale_version":"2026-10-v1"}'::jsonb)
on conflict(id) do nothing;

select public.refresh_release_health_status_v1();
