-- IFSI validated external sources batch 2
-- Respiratory system, Skin, ABO blood groups
-- Sources: MedlinePlus, NHS Blood and Transplant

update public.curriculum_lessons
set content='L’air entre par le nez ou la bouche, traverse le pharynx, le larynx et la trachée, puis gagne les bronches, les bronchioles et enfin les alvéoles. Les alvéoles sont le siège principal des échanges gazeux avec les capillaires pulmonaires : l’oxygène diffuse vers le sang tandis que le dioxyde de carbone diffuse du sang vers les alvéoles avant d’être expiré. Lors de l’inspiration, le diaphragme se contracte et s’abaisse, le volume thoracique augmente et la pression diminue, ce qui fait entrer l’air. Lors de l’expiration calme, le diaphragme se relâche et le volume thoracique diminue.',
source_files=coalesce(source_files,'[]'::jsonb)||jsonb_build_array(jsonb_build_object('label','MedlinePlus — Gas exchange','url','https://medlineplus.gov/ency/anatomyvideos/000059.htm','validation','institutional_validated'),jsonb_build_object('label','MedlinePlus — Breathing','url','https://medlineplus.gov/ency/anatomyvideos/000018.htm','validation','institutional_validated'),jsonb_build_object('label','MedlinePlus — Lung anatomy','url','https://medlineplus.gov/ency/imagepages/17100.htm','validation','institutional_validated')),updated_at=now()
where id='45bc76b1-4ba0-417e-934f-05d9c7c28201'::uuid;

update public.curriculum_lessons
set content='La peau est le plus grand organe du corps et participe notamment à la protection contre l’environnement, à la sensibilité et à la thermorégulation. Elle comprend trois grandes couches : l’épiderme en surface, le derme en profondeur intermédiaire et l’hypoderme en dessous. L’épiderme contient notamment des cellules produisant de la kératine et de la mélanine. Le derme contient des vaisseaux sanguins, des récepteurs sensoriels, des follicules pileux et des glandes. L’hypoderme contient notamment du tissu adipeux qui contribue à l’isolation thermique. La vasoconstriction cutanée participe à la conservation de chaleur lorsqu’il fait froid.',
source_files=coalesce(source_files,'[]'::jsonb)||jsonb_build_array(jsonb_build_object('label','MedlinePlus — Components of skin','url','https://medlineplus.gov/ency/anatomyvideos/000029.htm','validation','institutional_validated'),jsonb_build_object('label','MedlinePlus — Skin layers','url','https://medlineplus.gov/ency/imagepages/8912.htm','validation','institutional_validated')),updated_at=now()
where id='e8eacf16-2ca7-495a-acf2-aa0b6a1502f8'::uuid;

update public.curriculum_lessons
set content='Le système ABO classe le sang en groupes A, B, AB et O selon les antigènes présents à la surface des globules rouges. Le groupe O ne porte ni antigène A ni antigène B, tandis que le groupe AB porte les deux. La compatibilité transfusionnelle dépend de la correspondance entre les antigènes des globules rouges du donneur et les anticorps du receveur. Le groupe sanguin est hérité. Avant une transfusion, le laboratoire vérifie les groupes sanguins du patient et du donneur afin de réduire le risque d’incompatibilité. Pour les globules rouges, un patient AB+ peut recevoir des globules rouges de tous les groupes ABO/RhD de base, alors qu’un patient A- reçoit habituellement des globules rouges A- ou O-.',
source_files=coalesce(source_files,'[]'::jsonb)||jsonb_build_array(jsonb_build_object('label','NHS Blood and Transplant — Blood matching and antibodies','url','https://www.nhsbt.nhs.uk/what-we-do/clinical-and-research/blood-group-genotyping/hospital-and-lab-staff/frequently-asked-questions/','validation','institutional_validated'),jsonb_build_object('label','NHS Blood and Transplant — ABO groups and haemovigilance','url','https://www.nhsbt.nhs.uk/research-and-development/research-blogs/haemovigilance-qa-with-paula-bolton-maggs/','validation','institutional_validated')),updated_at=now()
where id='482b61ad-d525-48e1-970d-f40f33e0a96d'::uuid;

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,image_url,metadata)
values
('e0000001-71a0-4d01-9011-000000000001'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Où ont lieu principalement les échanges gazeux pulmonaires ?','Les échanges d’oxygène et de dioxyde de carbone se font principalement entre les alvéoles et les capillaires pulmonaires.','[{"text":"Au niveau des alvéoles","correct":true},{"text":"Au niveau du larynx","correct":false},{"text":"Au niveau du pharynx","correct":false},{"text":"Au niveau de la plèvre uniquement","correct":false}]'::jsonb,1,'MedlinePlus — Gas exchange',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000059.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000002'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Quel gaz diffuse des alvéoles vers le sang ?','L’oxygène diffuse des alvéoles vers les capillaires pulmonaires.','[{"text":"L’oxygène","correct":true},{"text":"Le dioxyde de carbone","correct":false},{"text":"L’azote uniquement","correct":false},{"text":"La vapeur d’eau uniquement","correct":false}]'::jsonb,1,'MedlinePlus — Gas exchange',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000059.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000003'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Quel gaz diffuse du sang vers les alvéoles ?','Le dioxyde de carbone passe du sang vers les alvéoles pour être ensuite expiré.','[{"text":"Le dioxyde de carbone","correct":true},{"text":"L’oxygène","correct":false},{"text":"Le sodium","correct":false},{"text":"Le glucose","correct":false}]'::jsonb,2,'MedlinePlus — Gas exchange',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000059.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000004'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Quel trajet de l’air est correct ?','L’air suit le trajet trachée, bronches, bronchioles puis alvéoles.','[{"text":"Trachée → bronches → bronchioles → alvéoles","correct":true},{"text":"Alvéoles → bronches → trachée → bronchioles","correct":false},{"text":"Trachée → alvéoles → bronchioles → bronches","correct":false},{"text":"Bronchioles → pharynx → alvéoles → trachée","correct":false}]'::jsonb,2,'MedlinePlus — Lung anatomy',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/17100.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000005'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Que fait le diaphragme lors de l’inspiration ?','Il se contracte et s’abaisse, ce qui augmente le volume thoracique.','[{"text":"Il se contracte et s’abaisse","correct":true},{"text":"Il se relâche et remonte immédiatement","correct":false},{"text":"Il ferme la trachée","correct":false},{"text":"Il bloque les bronches","correct":false}]'::jsonb,2,'MedlinePlus — Breathing',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000018.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000006'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Pourquoi l’air entre-t-il dans les poumons lors de l’inspiration ?','L’augmentation du volume thoracique diminue la pression à l’intérieur, ce qui favorise l’entrée d’air.','[{"text":"Parce que la pression thoracique diminue","correct":true},{"text":"Parce que la pression thoracique augmente fortement","correct":false},{"text":"Parce que les alvéoles produisent de l’air","correct":false},{"text":"Parce que les globules rouges aspirent l’air","correct":false}]'::jsonb,3,'MedlinePlus — Breathing',906,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000018.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000007'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Cas d’application — Une atteinte diffuse des alvéoles risque surtout de perturber quelle fonction ?','Les alvéoles assurent les échanges gazeux entre l’air et le sang.','[{"text":"Les échanges gazeux","correct":true},{"text":"La filtration rénale","correct":false},{"text":"La coagulation","correct":false},{"text":"La digestion mécanique","correct":false}]'::jsonb,3,'MedlinePlus — Gas exchange',907,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000059.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000008'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Cas d’application — Si le diaphragme ne peut plus s’abaisser correctement, quel phénomène sera directement gêné ?','L’abaissement du diaphragme contribue à augmenter le volume thoracique pendant l’inspiration.','[{"text":"L’inspiration","correct":true},{"text":"La coagulation","correct":false},{"text":"La filtration glomérulaire","correct":false},{"text":"La production de bile","correct":false}]'::jsonb,4,'MedlinePlus — Breathing',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000018.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000001-71a0-4d01-9011-000000000009'::uuid,'3da7b5be-2a6d-4381-ae10-f6998bdca68a'::uuid,'Quel enchaînement résume le mieux la fonction respiratoire ?','La ventilation renouvelle l’air alvéolaire puis les échanges gazeux permettent l’entrée d’oxygène dans le sang et l’élimination du dioxyde de carbone.','[{"text":"Ventilation puis échanges gazeux avec le sang","correct":true},{"text":"Digestion puis filtration du sang","correct":false},{"text":"Coagulation puis production de bile","correct":false},{"text":"Absorption intestinale puis ventilation","correct":false}]'::jsonb,5,'MedlinePlus — Gas exchange / Breathing',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000001'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Quelle est la couche la plus superficielle de la peau ?','L’épiderme constitue la couche externe de la peau.','[{"text":"L’épiderme","correct":true},{"text":"Le derme","correct":false},{"text":"L’hypoderme","correct":false},{"text":"Le périoste","correct":false}]'::jsonb,1,'MedlinePlus — Components of skin',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000029.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000002'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Quelle couche contient notamment de nombreux vaisseaux et récepteurs sensoriels ?','Le derme contient des vaisseaux sanguins et des récepteurs permettant de percevoir notamment pression, douleur et température.','[{"text":"Le derme","correct":true},{"text":"L’épiderme uniquement","correct":false},{"text":"La cornée","correct":false},{"text":"Le cartilage","correct":false}]'::jsonb,1,'MedlinePlus — Components of skin',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000029.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000003'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Quelle couche contient notamment du tissu adipeux participant à l’isolation thermique ?','L’hypoderme contient du tissu adipeux qui contribue à conserver la chaleur.','[{"text":"L’hypoderme","correct":true},{"text":"L’épiderme","correct":false},{"text":"La plèvre","correct":false},{"text":"L’endocarde","correct":false}]'::jsonb,2,'MedlinePlus — Components of skin',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000029.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000004'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Quel rôle majeur joue la peau ?','La peau protège l’organisme contre de nombreux agents extérieurs, notamment physiques, chimiques et microbiens.','[{"text":"La protection contre l’environnement","correct":true},{"text":"La filtration de l’urine","correct":false},{"text":"La production de bile","correct":false},{"text":"L’oxygénation du sang","correct":false}]'::jsonb,2,'MedlinePlus — Skin layers',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/8912.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000005'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Quel pigment cutané contribue à la protection contre les UV ?','La mélanine contribue à la pigmentation et participe à la protection vis-à-vis du rayonnement ultraviolet.','[{"text":"La mélanine","correct":true},{"text":"L’hémoglobine","correct":false},{"text":"La bile","correct":false},{"text":"La pepsine","correct":false}]'::jsonb,2,'MedlinePlus — Skin layers',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/8912.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000006'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Comment la peau participe-t-elle à conserver la chaleur lorsqu’il fait froid ?','La vasoconstriction des vaisseaux du derme limite les pertes de chaleur par la peau.','[{"text":"Par vasoconstriction cutanée","correct":true},{"text":"Par ouverture maximale de tous les vaisseaux cutanés","correct":false},{"text":"Par augmentation du péristaltisme","correct":false},{"text":"Par production de bile","correct":false}]'::jsonb,3,'MedlinePlus — Skin layers',906,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/8912.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000007'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Cas d’application — Une lésion profonde détruit de nombreux récepteurs du derme. Quelle fonction peut être perturbée ?','Le derme contient des récepteurs sensoriels impliqués dans la perception du toucher, de la douleur, de la pression et de la température.','[{"text":"La sensibilité cutanée","correct":true},{"text":"La filtration glomérulaire","correct":false},{"text":"La production d’insuline","correct":false},{"text":"La ventilation alvéolaire","correct":false}]'::jsonb,3,'MedlinePlus — Components of skin',907,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000029.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000008'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Cas d’application — Une perte importante de tissu sous-cutané peut réduire quelle fonction ?','Le tissu adipeux de l’hypoderme contribue à l’isolation thermique.','[{"text":"L’isolation thermique","correct":true},{"text":"La production de globules rouges","correct":false},{"text":"La sécrétion de glucagon","correct":false},{"text":"La diffusion alvéolaire","correct":false}]'::jsonb,4,'MedlinePlus — Components of skin',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/anatomyvideos/000029.htm","source_validation":"institutional_validated"}'::jsonb),
('e0000002-71a0-4d01-9011-000000000009'::uuid,'1b1e3b17-4a47-4bdb-8c81-dd45331c5d39'::uuid,'Quel ensemble décrit le mieux les grandes fonctions de la peau ?','La peau assure à la fois protection, sensibilité et participation à la régulation thermique.','[{"text":"Protection, sensibilité et thermorégulation","correct":true},{"text":"Filtration rénale, digestion et ventilation","correct":false},{"text":"Coagulation, bile et audition","correct":false},{"text":"Vision, péristaltisme et diurèse","correct":false}]'::jsonb,5,'MedlinePlus — Components of skin / Skin layers',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000001'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Quels sont les quatre groupes du système ABO ?','Le système ABO distingue les groupes A, B, AB et O.','[{"text":"A, B, AB et O","correct":true},{"text":"A, C, D et O","correct":false},{"text":"AB, CD, EF et O","correct":false},{"text":"A, B, C et D","correct":false}]'::jsonb,1,'NHS Blood and Transplant — ABO groups',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000002'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Que porte un globule rouge de groupe A dans le système ABO ?','Le groupe A se caractérise par la présence de l’antigène A sur les globules rouges.','[{"text":"L’antigène A","correct":true},{"text":"L’antigène B uniquement","correct":false},{"text":"Aucun antigène ABO","correct":false},{"text":"Les antigènes A et B","correct":false}]'::jsonb,1,'NHS Blood and Transplant — Blood groups',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000003'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Que porte un globule rouge de groupe AB ?','Les globules rouges du groupe AB portent les antigènes A et B.','[{"text":"Les antigènes A et B","correct":true},{"text":"Uniquement l’antigène A","correct":false},{"text":"Uniquement l’antigène B","correct":false},{"text":"Aucun antigène ABO","correct":false}]'::jsonb,2,'NHS Blood and Transplant — ABO groups',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000004'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Que caractérise le groupe O dans le système ABO ?','Le groupe O ne porte ni antigène A ni antigène B à la surface des globules rouges.','[{"text":"Absence d’antigènes A et B","correct":true},{"text":"Présence des antigènes A et B","correct":false},{"text":"Présence de l’antigène A uniquement","correct":false},{"text":"Présence de l’antigène B uniquement","correct":false}]'::jsonb,2,'NHS Blood and Transplant — ABO groups',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000005'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Pourquoi vérifie-t-on les groupes sanguins avant une transfusion ?','Une incompatibilité ABO peut provoquer une réaction transfusionnelle grave ; le groupe donneur doit donc être compatible avec celui du receveur.','[{"text":"Pour éviter une incompatibilité transfusionnelle","correct":true},{"text":"Pour mesurer la glycémie","correct":false},{"text":"Pour évaluer la ventilation","correct":false},{"text":"Pour déterminer le groupe musculaire","correct":false}]'::jsonb,2,'NHS Blood and Transplant — Blood matching',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.nhsbt.nhs.uk/what-we-do/clinical-and-research/blood-group-genotyping/hospital-and-lab-staff/frequently-asked-questions/","source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000006'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Le groupe sanguin ABO est-il en partie hérité ?','Les groupes sanguins sont hérités des parents.','[{"text":"Oui","correct":true},{"text":"Non, il est déterminé uniquement par l’alimentation","correct":false},{"text":"Non, il change à chaque infection","correct":false},{"text":"Non, il dépend uniquement de l’âge","correct":false}]'::jsonb,3,'NHS Blood and Transplant — Blood matching and antibodies',906,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.nhsbt.nhs.uk/what-we-do/clinical-and-research/blood-group-genotyping/hospital-and-lab-staff/frequently-asked-questions/","source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000007'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Cas d’application — Un patient A- a besoin de globules rouges. Quelle proposition est compatible selon les groupes de base ?','NHS Blood and Transplant indique qu’un patient A- peut recevoir des globules rouges A- ou O-.','[{"text":"A- ou O-","correct":true},{"text":"B+ ou AB+","correct":false},{"text":"AB- uniquement","correct":false},{"text":"B- uniquement","correct":false}]'::jsonb,3,'NHS Blood and Transplant — Blood donation information',907,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.nhsbt.nhs.uk/how-you-can-help/get-involved/key-messages-and-information/blood-donation-key-messages-and-information/","source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000008'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Cas d’application — Pourquoi une erreur d’identification ABO avant transfusion est-elle particulièrement dangereuse ?','Une incompatibilité ABO peut conduire les anticorps du receveur ou du plasma transfusé à réagir contre les globules rouges incompatibles.','[{"text":"Parce qu’elle peut déclencher une réaction transfusionnelle grave","correct":true},{"text":"Parce qu’elle provoque toujours une hypoglycémie isolée","correct":false},{"text":"Parce qu’elle bloque uniquement la digestion","correct":false},{"text":"Parce qu’elle empêche uniquement la sudation","correct":false}]'::jsonb,4,'NHS Blood and Transplant — Haemovigilance',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.nhsbt.nhs.uk/research-and-development/research-blogs/haemovigilance-qa-with-paula-bolton-maggs/","source_validation":"institutional_validated"}'::jsonb),
('e0000003-71a0-4d01-9011-000000000009'::uuid,'8bd9d456-f10d-4a69-aac2-82ddf74607f4'::uuid,'Quel raisonnement résume le mieux la sécurité transfusionnelle ABO ?','Il faut identifier correctement le groupe du patient puis sélectionner un produit sanguin compatible avant transfusion.','[{"text":"Identifier le groupe puis vérifier la compatibilité du produit","correct":true},{"text":"Transfuser avant de connaître le groupe","correct":false},{"text":"Utiliser toujours le même groupe pour tous les patients","correct":false},{"text":"Ignorer les antigènes des globules rouges","correct":false}]'::jsonb,5,'NHS Blood and Transplant — Blood matching',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb)
on conflict(id) do nothing;

select public.refresh_release_health_status_v1();
