-- Progressive quiz enrichment batch 6
-- ES1 functional application and integration

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,metadata)
values
('aaaaaaa1-71a0-4d01-9006-000000000001','2dd7235d-77d5-4583-a0a9-a90064a0f74e',
'Un paciente mantiene una contracción muscular sin producir un gran movimiento articular. ¿Qué conclusión es la más adecuada?',
'Un músculo puede activarse y producir fuerza sin generar un gran desplazamiento. Activación muscular y amplitud de movimiento no son equivalentes.',
'[{"text":"Puede existir activación muscular sin gran desplazamiento articular","correct":true},{"text":"Si no hay movimiento, no existe actividad muscular","correct":false},{"text":"La amplitud articular mide directamente la fuerza muscular","correct":false},{"text":"Toda contracción produce siempre movimiento visible","correct":false}]'::jsonb,
4,'UVic-UCC — Fisiología I 2026-2027',981,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000002','2dd7235d-77d5-4583-a0a9-a90064a0f74e',
'Caso de integración básica — Durante un ejercicio aumenta la fatiga y empeora la calidad del movimiento aunque el músculo sigue contrayéndose. ¿Qué dato debe guiar la adaptación de la carga?',
'La respuesta al esfuerzo, la fatiga y la recuperación deben interpretarse junto con la tarea funcional; la contracción aislada no resume el rendimiento global.',
'[{"text":"La tolerancia, la fatiga y la calidad funcional del movimiento","correct":true},{"text":"Solo la presencia de contracción","correct":false},{"text":"Solo el número de repeticiones previstas","correct":false},{"text":"Ignorar la recuperación entre esfuerzos","correct":false}]'::jsonb,
5,'UVic-UCC — Fisiología I 2026-2027',982,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000003','e2a03bd6-41d0-49a0-af44-8ea20fb32e66',
'Un paciente refiere dolor durante la contracción contra resistencia, pero no sensación clara de inestabilidad articular. ¿Qué estructura merece especial atención en la exploración?',
'El tendón transmite la fuerza del músculo al hueso y una lesión tendinosa puede manifestarse especialmente con dolor durante la contracción o la carga.',
'[{"text":"El tendón","correct":true},{"text":"Solo el ligamento","correct":false},{"text":"Únicamente el cartílago","correct":false},{"text":"Ninguna estructura relacionada con la carga","correct":false}]'::jsonb,
4,'MedlinePlus — Tendones y ligamentos',981,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000004','e2a03bd6-41d0-49a0-af44-8ea20fb32e66',
'Caso de integración básica — Tras un traumatismo, el paciente describe sensación de fallo articular además de dolor. ¿Qué enfoque es más correcto?',
'La estabilidad debe interpretarse junto con historia, observación, movimiento y respuesta funcional. Un síntoma aislado no permite concluir un diagnóstico.',
'[{"text":"Explorar estabilidad y función integrando varios datos clínicos","correct":true},{"text":"Diagnosticar solo por la palabra “fallo”","correct":false},{"text":"Ignorar la historia del traumatismo","correct":false},{"text":"Valorar únicamente el dolor en reposo","correct":false}]'::jsonb,
5,'MedlinePlus — Tendones y ligamentos',982,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000005','ab13dc74-5dd6-43bb-833b-1f90824ab765',
'Un ejercicio pretende mejorar la capacidad de levantarse de una silla. ¿Qué criterio hace que la elección sea coherente?',
'El ejercicio terapéutico debe relacionarse con un objetivo funcional observable y con la capacidad actual de la persona.',
'[{"text":"Que la tarea elegida se relacione con el objetivo funcional","correct":true},{"text":"Que sea el ejercicio más difícil disponible","correct":false},{"text":"Que use siempre resistencia externa","correct":false},{"text":"Que no se observe la tolerancia","correct":false}]'::jsonb,
4,'UVic-UCC — Bases de la Pràctica en Fisioteràpia 2026-2027',981,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000006','ab13dc74-5dd6-43bb-833b-1f90824ab765',
'Caso de integración básica — Al aumentar la dificultad de un ejercicio aparece dolor excesivo y pérdida de control. ¿Cuál es la mejor decisión?',
'La progresión debe ser gradual y la respuesta del paciente sirve para decidir si mantener, facilitar o aumentar la dificultad.',
'[{"text":"Reducir la dificultad y reevaluar la tolerancia","correct":true},{"text":"Aumentar aún más la carga","correct":false},{"text":"Mantener el ejercicio sin observar la respuesta","correct":false},{"text":"Ignorar la pérdida de control","correct":false}]'::jsonb,
5,'UVic-UCC — Bases de la Pràctica en Fisioteràpia 2026-2027',982,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000007','da2cf746-0f04-4910-9690-47067d07ea22',
'Antes de una actividad, un signo vital está algo alejado del valor habitual del paciente. ¿Qué enfoque es el más adecuado?',
'Un valor aislado debe interpretarse con el contexto, el estado basal, la tendencia y la técnica de medición.',
'[{"text":"Compararlo con el basal, el contexto y la tendencia antes de decidir","correct":true},{"text":"Tomarlo como diagnóstico por sí solo","correct":false},{"text":"Ignorar cómo se realizó la medición","correct":false},{"text":"Usar únicamente un valor aislado","correct":false}]'::jsonb,
4,'MedlinePlus — Signos vitales',981,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000008','da2cf746-0f04-4910-9690-47067d07ea22',
'Caso de integración básica — Durante el ejercicio cambian varios signos vitales y aparecen síntomas nuevos. ¿Qué debe hacerse antes de progresar la actividad?',
'Los signos vitales ayudan a decidir si una actividad es apropiada, si debe adaptarse o si se requiere una valoración adicional.',
'[{"text":"Detener o adaptar la actividad y reevaluar la situación","correct":true},{"text":"Progresar automáticamente porque el ejercicio ya empezó","correct":false},{"text":"Ignorar los síntomas y mirar solo la frecuencia cardiaca","correct":false},{"text":"Esperar a terminar todas las repeticiones previstas","correct":false}]'::jsonb,
5,'MedlinePlus — Signos vitales',982,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000009','ff9d15e0-3905-460e-b9e8-577adfc98316',
'Un paciente tiene menos dorsiflexión de tobillo y modifica su forma de caminar. ¿Qué descripción clínica es más útil?',
'La movilidad debe describirse por articulación, movimiento, lado, amplitud, síntomas y repercusión funcional.',
'[{"text":"Relacionar la limitación de dorsiflexión con la marcha y los síntomas","correct":true},{"text":"Anotar solo “tobillo rígido”","correct":false},{"text":"Concluir una causa sin explorar","correct":false},{"text":"Ignorar la repercusión funcional","correct":false}]'::jsonb,
4,'MedlinePlus — Rango de movimiento limitado',981,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb),
('aaaaaaa1-71a0-4d01-9006-000000000010','ff9d15e0-3905-460e-b9e8-577adfc98316',
'Caso de integración básica — El rango articular mejora, pero la tarea funcional sigue limitada. ¿Qué interpretación es la más correcta?',
'Un cambio de amplitud debe relacionarse con la función. Mejorar un dato aislado no garantiza que la tarea funcional se haya normalizado.',
'[{"text":"Reevaluar cómo utiliza ese rango durante la tarea funcional","correct":true},{"text":"Concluir que la función ya está recuperada","correct":false},{"text":"Dejar de observar la marcha","correct":false},{"text":"Valorar únicamente el rango pasivo","correct":false}]'::jsonb,
5,'MedlinePlus — Rango de movimiento limitado',982,'source_validated',true,'clinical_case','[]'::jsonb,'{"enrichment_batch":"progressive_quiz_v6","difficulty_scale_version":"2026-10-v1"}'::jsonb)
on conflict(id) do nothing;

select public.refresh_release_health_status_v1();
