-- IFSI validated external sources batch 3
-- Hemostasis, Thermoregulation, Calcium homeostasis
-- Sources: MedlinePlus, NIH ODS, NCBI Bookshelf

update public.curriculum_lessons
set content='L’hémostase correspond aux mécanismes qui limitent le saignement après une lésion vasculaire. Les plaquettes adhèrent rapidement à la zone lésée et s’agrègent pour former un premier clou plaquettaire. Elles libèrent aussi des médiateurs qui participent à l’activation de la coagulation. Les facteurs de coagulation sont des protéines sanguines qui s’activent en cascade et conduisent notamment à la formation de fibrine, laquelle stabilise le caillot. La plupart des facteurs de coagulation sont produits par le foie. Un déficit plaquettaire ou un déficit en facteurs de coagulation peut augmenter le risque de saignement, tandis qu’une coagulation excessive peut favoriser la formation de thromboses.',
source_files=coalesce(source_files,'[]'::jsonb)||jsonb_build_array(
jsonb_build_object('label','MedlinePlus — Coagulation Factor Tests','url','https://medlineplus.gov/lab-tests/coagulation-factor-tests/','validation','institutional_validated'),
jsonb_build_object('label','MedlinePlus — Blood clot formation','url','https://medlineplus.gov/ency/imagepages/19462.htm','validation','institutional_validated'),
jsonb_build_object('label','MedlinePlus — Platelet Tests','url','https://medlineplus.gov/lab-tests/platelet-tests/','validation','institutional_validated')
),updated_at=now()
where id='bc98f561-3e70-47fd-8ba9-f3781240b12f'::uuid;

update public.curriculum_lessons
set content='La thermorégulation permet de maintenir une température corporelle compatible avec le fonctionnement normal de l’organisme. La sudation aide à refroidir le corps, notamment lorsque la température ambiante augmente ou pendant l’exercice. La transpiration est contrôlée par le système nerveux autonome. Lorsqu’il fait froid, les vaisseaux sanguins superficiels de la peau se contractent afin de réduire les pertes de chaleur et de maintenir la température centrale. À l’inverse, en ambiance chaude, l’augmentation du débit sanguin cutané et la sudation favorisent la dissipation thermique. Une forte humidité réduit l’efficacité du refroidissement par évaporation de la sueur.',
source_files=coalesce(source_files,'[]'::jsonb)||jsonb_build_array(
jsonb_build_object('label','MedlinePlus — Sweating','url','https://medlineplus.gov/ency/article/003218.htm','validation','institutional_validated'),
jsonb_build_object('label','MedlinePlus — Skin layers','url','https://medlineplus.gov/ency/imagepages/8912.htm','validation','institutional_validated'),
jsonb_build_object('label','MedlinePlus — Avoid overheating during exercise','url','https://medlineplus.gov/ency/patientinstructions/000865.htm','validation','institutional_validated')
),updated_at=now()
where id='a7f7db84-5d59-4b88-8e48-65a19afefcd9'::uuid;

update public.curriculum_lessons
set content='La calcémie est étroitement régulée afin de maintenir la concentration de calcium sanguin dans une plage compatible avec le fonctionnement neuromusculaire et cellulaire. La parathormone (PTH), sécrétée par les glandes parathyroïdes, joue un rôle majeur lorsque la calcémie baisse. Elle favorise notamment la mobilisation du calcium osseux, la réabsorption rénale du calcium et la production rénale de calcitriol, forme active de la vitamine D. Le calcitriol augmente notamment l’absorption intestinale du calcium. Lorsque la calcémie remonte, la sécrétion de PTH diminue par rétrocontrôle. La majeure partie du calcium corporel est stockée dans les os, qui constituent un important réservoir.',
source_files=coalesce(source_files,'[]'::jsonb)||jsonb_build_array(
jsonb_build_object('label','NIH Office of Dietary Supplements — Calcium Fact Sheet','url','https://ods.od.nih.gov/factsheets/calcium-HealthProfessional/','validation','institutional_validated'),
jsonb_build_object('label','NIH Office of Dietary Supplements — Vitamin D Fact Sheet','url','https://ods.od.nih.gov/factsheets/vitaminD-HealthProfessional/','validation','institutional_validated'),
jsonb_build_object('label','NCBI Bookshelf — Homeostatic Regulation of Calcium','url','https://www.ncbi.nlm.nih.gov/books/NBK56060/','validation','institutional_reference')
),updated_at=now()
where id='d48b72f7-82ca-4511-8401-61c89630f097'::uuid;

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,image_url,metadata)
values
('f0000001-71a0-4d01-9012-000000000001'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Quel élément intervient très tôt après une lésion vasculaire pour limiter le saignement ?','Les plaquettes adhèrent rapidement à la zone lésée et participent à la formation du clou plaquettaire.','[{"text":"Les plaquettes","correct":true},{"text":"Les pneumocytes","correct":false},{"text":"Les hépatocytes uniquement","correct":false},{"text":"Les neurones","correct":false}]'::jsonb,1,'MedlinePlus — Blood clot formation',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/19462.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000002'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Quel est le rôle principal de la fibrine dans l’hémostase ?','La fibrine forme un réseau qui consolide et stabilise le caillot.','[{"text":"Stabiliser le caillot","correct":true},{"text":"Transporter l’oxygène","correct":false},{"text":"Produire l’insuline","correct":false},{"text":"Assurer la filtration rénale","correct":false}]'::jsonb,1,'MedlinePlus — Blood clot formation',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/19462.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000003'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Que sont les facteurs de coagulation ?','Ce sont des protéines sanguines qui participent à une cascade de réactions aboutissant à la formation d’un caillot stable.','[{"text":"Des protéines de la coagulation","correct":true},{"text":"Des cellules musculaires","correct":false},{"text":"Des hormones digestives","correct":false},{"text":"Des pigments cutanés","correct":false}]'::jsonb,2,'MedlinePlus — Coagulation Factor Tests',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/lab-tests/coagulation-factor-tests/","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000004'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Quel organe produit la majorité des facteurs de coagulation ?','La plupart des facteurs de coagulation sont synthétisés par le foie.','[{"text":"Le foie","correct":true},{"text":"La vessie","correct":false},{"text":"La trachée","correct":false},{"text":"Le pancréas exocrine uniquement","correct":false}]'::jsonb,2,'MedlinePlus — Coagulation Factor Tests',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/lab-tests/coagulation-factor-tests/","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000005'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Quelle conséquence peut avoir une thrombopénie importante ?','Une diminution importante du nombre de plaquettes peut réduire la capacité à former un clou plaquettaire et augmenter le risque de saignement.','[{"text":"Un risque accru de saignement","correct":true},{"text":"Une augmentation obligatoire de la calcémie","correct":false},{"text":"Une amélioration automatique de la coagulation","correct":false},{"text":"Une hausse systématique de la ventilation","correct":false}]'::jsonb,2,'MedlinePlus — Platelet Tests',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/lab-tests/platelet-tests/","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000006'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Cas d’application — Un patient a un nombre normal de plaquettes mais un déficit sévère d’un facteur de coagulation. Peut-il saigner davantage ?','Oui. Un déficit d’un facteur de coagulation peut empêcher la formation correcte d’un caillot stable même si le nombre de plaquettes est normal.','[{"text":"Oui, la coagulation peut rester insuffisante","correct":true},{"text":"Non, les plaquettes suffisent toujours à elles seules","correct":false},{"text":"Non, les facteurs de coagulation ne servent pas à l’hémostase","correct":false},{"text":"Oui, uniquement parce que la glycémie baisse","correct":false}]'::jsonb,3,'MedlinePlus — Coagulation Factor Tests',906,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/lab-tests/coagulation-factor-tests/","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000007'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Quel enchaînement est le plus cohérent après une lésion vasculaire ?','Les plaquettes forment d’abord un clou puis la coagulation génère un réseau de fibrine qui stabilise l’ensemble.','[{"text":"Adhésion plaquettaire puis stabilisation par la fibrine","correct":true},{"text":"Production d’insuline puis coagulation","correct":false},{"text":"Filtration rénale puis agrégation plaquettaire","correct":false},{"text":"Ventilation puis formation de fibrine","correct":false}]'::jsonb,3,'MedlinePlus — Blood clot formation',907,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/19462.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000008'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Cas d’application — Pourquoi une coagulation excessive peut-elle devenir dangereuse ?','Un caillot formé dans un vaisseau peut gêner ou bloquer la circulation sanguine et entraîner des complications graves.','[{"text":"Parce qu’un thrombus peut obstruer un vaisseau","correct":true},{"text":"Parce qu’elle augmente toujours la production de bile","correct":false},{"text":"Parce qu’elle supprime la ventilation","correct":false},{"text":"Parce qu’elle détruit systématiquement les plaquettes","correct":false}]'::jsonb,4,'MedlinePlus — Blood Clots',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/bloodclots.html","source_validation":"institutional_validated"}'::jsonb),
('f0000001-71a0-4d01-9012-000000000009'::uuid,'ec2644cf-13e6-42c8-9cb0-6c2c539d93d3'::uuid,'Quel raisonnement résume le mieux l’hémostase normale ?','Elle associe une réponse plaquettaire et une cascade de coagulation pour arrêter le saignement sans favoriser une thrombose excessive.','[{"text":"Équilibrer arrêt du saignement et limitation de la thrombose","correct":true},{"text":"Former le plus de caillots possible","correct":false},{"text":"Supprimer toute activité plaquettaire","correct":false},{"text":"Utiliser uniquement la fibrine sans plaquettes","correct":false}]'::jsonb,5,'MedlinePlus — Coagulation and Blood Clots',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000001'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Quel mécanisme aide directement le corps à se refroidir quand il fait chaud ?','La sudation permet une perte de chaleur, surtout lorsque la sueur s’évapore à la surface de la peau.','[{"text":"La sudation","correct":true},{"text":"La coagulation","correct":false},{"text":"La production de bile","correct":false},{"text":"La filtration glomérulaire","correct":false}]'::jsonb,1,'MedlinePlus — Sweating',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/article/003218.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000002'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Quel système contrôle principalement la sudation ?','La sudation est contrôlée par le système nerveux autonome.','[{"text":"Le système nerveux autonome","correct":true},{"text":"Le système ABO","correct":false},{"text":"Le système biliaire","correct":false},{"text":"Le système de coagulation","correct":false}]'::jsonb,1,'MedlinePlus — Sweating',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/article/003218.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000003'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Que font les vaisseaux cutanés lorsqu’il fait froid ?','Ils se contractent afin de réduire le débit sanguin superficiel et limiter les pertes de chaleur.','[{"text":"Ils se contractent","correct":true},{"text":"Ils se dilatent systématiquement","correct":false},{"text":"Ils disparaissent","correct":false},{"text":"Ils deviennent des glandes sudoripares","correct":false}]'::jsonb,2,'MedlinePlus — Skin layers',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/8912.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000004'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Pourquoi la vasoconstriction cutanée aide-t-elle à conserver la chaleur ?','Elle réduit la quantité de sang chaud envoyée près de la surface de la peau et limite ainsi les pertes thermiques.','[{"text":"Elle réduit les pertes de chaleur par la peau","correct":true},{"text":"Elle augmente toujours la sudation","correct":false},{"text":"Elle augmente la filtration rénale","correct":false},{"text":"Elle augmente la production de fibrine","correct":false}]'::jsonb,2,'MedlinePlus — Skin layers',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/imagepages/8912.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000005'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Pourquoi une forte humidité peut-elle rendre le refroidissement plus difficile ?','Lorsque l’air est très humide, la sueur s’évapore moins efficacement et le refroidissement cutané diminue.','[{"text":"Parce que l’évaporation de la sueur est moins efficace","correct":true},{"text":"Parce que le sang ne contient plus d’oxygène","correct":false},{"text":"Parce que les plaquettes ne coagulent plus","correct":false},{"text":"Parce que la PTH disparaît","correct":false}]'::jsonb,3,'MedlinePlus — Avoid overheating during exercise',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/patientinstructions/000865.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000006'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Cas d’application — Lors d’un exercice par forte chaleur, quel changement participe au refroidissement ?','L’organisme augmente notamment le débit sanguin vers la peau et la sudation pour dissiper davantage de chaleur.','[{"text":"Augmentation du débit cutané et de la sudation","correct":true},{"text":"Suppression de toute sudation","correct":false},{"text":"Vasoconstriction cutanée maximale","correct":false},{"text":"Réduction obligatoire de la fréquence cardiaque","correct":false}]'::jsonb,3,'MedlinePlus — Avoid overheating during exercise',906,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/patientinstructions/000865.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000007'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Cas d’application — Une personne transpire beaucoup pendant un exercice prolongé. Quel risque immédiat faut-il aussi surveiller ?','Une sudation importante entraîne des pertes d’eau et d’électrolytes, ce qui peut favoriser la déshydratation.','[{"text":"La déshydratation","correct":true},{"text":"Une polyglobulie immédiate certaine","correct":false},{"text":"Une absence totale de pertes hydriques","correct":false},{"text":"Une augmentation automatique de la calcémie","correct":false}]'::jsonb,3,'MedlinePlus — Sweating',907,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/article/003218.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000008'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Cas d’application — Une exposition prolongée au froid provoque une forte vasoconstriction des extrémités. Quel est l’objectif principal ?','L’organisme cherche à limiter les pertes de chaleur et à préserver la température centrale au bénéfice des organes vitaux.','[{"text":"Préserver la température centrale","correct":true},{"text":"Augmenter les pertes thermiques","correct":false},{"text":"Accroître la sudation périphérique","correct":false},{"text":"Diminuer la coagulation","correct":false}]'::jsonb,4,'MedlinePlus — Cold exposure and vasoconstriction',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/ency/patientinstructions/000866.htm","source_validation":"institutional_validated"}'::jsonb),
('f0000002-71a0-4d01-9012-000000000009'::uuid,'daf418af-f0bc-4df7-9273-1b55d7fce582'::uuid,'Quel raisonnement résume le mieux la thermorégulation ?','Elle adapte les pertes et la conservation de chaleur grâce notamment à la sudation et aux modifications du débit sanguin cutané.','[{"text":"Adapter la dissipation et la conservation de chaleur selon le contexte","correct":true},{"text":"Maintenir toujours une vasoconstriction maximale","correct":false},{"text":"Supprimer la sudation en ambiance chaude","correct":false},{"text":"Utiliser uniquement les reins pour réguler la température","correct":false}]'::jsonb,5,'MedlinePlus — Thermoregulation mechanisms',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000001'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Quelle hormone joue un rôle majeur lorsque la calcémie baisse ?','La parathormone ou PTH est sécrétée par les glandes parathyroïdes lorsque la concentration de calcium sanguin diminue.','[{"text":"La PTH","correct":true},{"text":"L’insuline","correct":false},{"text":"Le glucagon","correct":false},{"text":"La bilirubine","correct":false}]'::jsonb,1,'NCBI Bookshelf — Homeostatic Regulation of Calcium',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.ncbi.nlm.nih.gov/books/NBK56060/","source_validation":"institutional_reference"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000002'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Quel organe stocke la majeure partie du calcium corporel ?','La quasi-totalité du calcium de l’organisme est stockée dans les os et les dents, les os constituant un important réservoir mobilisable.','[{"text":"Le squelette","correct":true},{"text":"Le foie","correct":false},{"text":"Le pancréas","correct":false},{"text":"Les poumons","correct":false}]'::jsonb,1,'NIH ODS — Calcium Fact Sheet',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://ods.od.nih.gov/factsheets/calcium-HealthProfessional/","source_validation":"institutional_validated"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000003'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Quel rôle joue la vitamine D dans l’équilibre du calcium ?','La vitamine D est nécessaire à une absorption intestinale efficace du calcium et contribue au maintien d’une calcémie adéquate.','[{"text":"Elle favorise l’absorption intestinale du calcium","correct":true},{"text":"Elle bloque toute absorption du calcium","correct":false},{"text":"Elle transforme le calcium en glucose","correct":false},{"text":"Elle remplace la PTH dans toutes ses fonctions","correct":false}]'::jsonb,2,'NIH ODS — Calcium Fact Sheet',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://ods.od.nih.gov/factsheets/calcium-HealthProfessional/","source_validation":"institutional_validated"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000004'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Sous l’effet de la PTH, quel organe augmente la production de calcitriol ?','La PTH stimule le rein à produire davantage de calcitriol, la forme hormonale active de la vitamine D.','[{"text":"Le rein","correct":true},{"text":"La rate","correct":false},{"text":"Le côlon","correct":false},{"text":"La trachée","correct":false}]'::jsonb,2,'NCBI Bookshelf — Homeostatic Regulation of Calcium',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.ncbi.nlm.nih.gov/books/NBK56060/","source_validation":"institutional_reference"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000005'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Quel effet la PTH exerce-t-elle sur le rein vis-à-vis du calcium ?','La PTH augmente la réabsorption rénale du calcium, ce qui limite son élimination urinaire.','[{"text":"Elle augmente la réabsorption rénale du calcium","correct":true},{"text":"Elle bloque toute réabsorption du calcium","correct":false},{"text":"Elle augmente uniquement l’élimination du glucose","correct":false},{"text":"Elle produit de la fibrine","correct":false}]'::jsonb,2,'NCBI Bookshelf — Homeostatic Regulation of Calcium',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.ncbi.nlm.nih.gov/books/NBK56060/","source_validation":"institutional_reference"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000006'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Que se passe-t-il lorsque la calcémie remonte après l’action de la PTH ?','Le rétrocontrôle lié à l’augmentation du calcium sanguin réduit la sécrétion de PTH.','[{"text":"La sécrétion de PTH diminue","correct":true},{"text":"La sécrétion de PTH augmente sans limite","correct":false},{"text":"Le rein cesse toute fonction","correct":false},{"text":"La vitamine D disparaît du sang","correct":false}]'::jsonb,3,'NCBI Bookshelf — Homeostatic Regulation of Calcium',906,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.ncbi.nlm.nih.gov/books/NBK56060/","source_validation":"institutional_reference"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000007'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Cas d’application — Une hypocalcémie stimule la sécrétion de PTH. Quelle combinaison est cohérente ?','La PTH favorise à la fois la réabsorption rénale du calcium, la production de calcitriol et la mobilisation de calcium à partir de l’os.','[{"text":"Réabsorption rénale + calcitriol + mobilisation osseuse","correct":true},{"text":"Blocage du rein + arrêt du calcitriol","correct":false},{"text":"Suppression de toute mobilisation osseuse","correct":false},{"text":"Production d’insuline + sudation","correct":false}]'::jsonb,3,'NCBI Bookshelf — Homeostatic Regulation of Calcium',907,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.ncbi.nlm.nih.gov/books/NBK56060/","source_validation":"institutional_reference"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000008'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Cas d’application — Une carence sévère en vitamine D peut perturber la calcémie principalement par quel mécanisme ?','Une carence en vitamine D peut diminuer l’absorption intestinale du calcium et perturber l’équilibre calcique.','[{"text":"Diminution de l’absorption intestinale du calcium","correct":true},{"text":"Augmentation systématique de la fibrine","correct":false},{"text":"Arrêt de toute ventilation","correct":false},{"text":"Augmentation obligatoire du groupe sanguin ABO","correct":false}]'::jsonb,4,'NIH ODS — Calcium and Vitamin D Fact Sheets',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://ods.od.nih.gov/factsheets/vitaminD-HealthProfessional/","source_validation":"institutional_validated"}'::jsonb),
('f0000003-71a0-4d01-9012-000000000009'::uuid,'f369685b-5187-4832-894d-95e3593113eb'::uuid,'Quel raisonnement résume le mieux la régulation de la calcémie ?','La calcémie résulte d’un équilibre entre os, rein et intestin sous contrôle hormonal, notamment de la PTH et du système de la vitamine D.','[{"text":"Coordination entre os, rein et intestin sous contrôle hormonal","correct":true},{"text":"Régulation uniquement par les poumons","correct":false},{"text":"Régulation uniquement par le foie","correct":false},{"text":"Absence de rétrocontrôle hormonal","correct":false}]'::jsonb,5,'NIH/NCBI — Calcium homeostasis',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_validation":"institutional_validated"}'::jsonb)
on conflict(id) do nothing;

select public.refresh_release_health_status_v1();
