-- IFSI validated external sources batch 1
-- Sources: NIDDK/NIH, MedlinePlus/NIH, MSD professional reference.
-- Completes Digestive system, Endocrine system, and Blood glucose regulation to >=10 validated questions.

update public.curriculum_lessons
set content='L’appareil digestif comprend le tube digestif, de la bouche à l’anus, ainsi que des organes annexes comme le foie, le pancréas et la vésicule biliaire. La digestion associe des mouvements mécaniques, notamment la mastication et le péristaltisme, à l’action des sucs digestifs. L’intestin grêle assure l’essentiel de l’absorption des nutriments. Le gros intestin absorbe notamment de l’eau et transforme progressivement le contenu digestif en selles. Le foie produit la bile, la vésicule biliaire la stocke et le pancréas sécrète des enzymes digestives. Les nerfs et les hormones participent aussi à la régulation du processus digestif.',
    source_files=coalesce(source_files,'[]'::jsonb) || jsonb_build_array(
      jsonb_build_object('label','NIDDK/NIH — Your Digestive System & How it Works','url','https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works','validation','institutional_validated'),
      jsonb_build_object('label','MedlinePlus — Anatomie / appareil digestif','url','https://medlineplus.gov/spanish/anatomy.html','validation','institutional_validated')
    ),
    updated_at=now()
where id='683a7e3f-d2ba-487b-95c1-74f5b2f65612'::uuid;

update public.curriculum_lessons
set content='Le système endocrinien regroupe des glandes qui sécrètent des hormones dans la circulation sanguine. Les hormones agissent comme des messagers chimiques sur des cellules ou organes cibles possédant des récepteurs adaptés. Elles participent notamment à la croissance, au métabolisme, à la reproduction, à l’équilibre hydrique, à la réponse au stress et à la régulation de la température. Un trouble endocrinien peut résulter d’une production hormonale trop faible ou trop importante, d’un dysfonctionnement de la glande ou d’une réponse anormale du tissu cible.',
    source_files=coalesce(source_files,'[]'::jsonb) || jsonb_build_array(
      jsonb_build_object('label','MedlinePlus/NIH — Endocrine Diseases','url','https://medlineplus.gov/endocrinediseases.html','validation','institutional_validated'),
      jsonb_build_object('label','Manuel MSD professionnel — Revue générale du système endocrinien','url','https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien','validation','peer_reviewed_reference')
    ),
    updated_at=now()
where id='9894e538-f334-462d-84b1-47ee5510308a'::uuid;

update public.curriculum_lessons
set content='La glycémie correspond à la concentration de glucose dans le sang. Sa régulation repose en grande partie sur l’action coordonnée de l’insuline et du glucagon, deux hormones produites par le pancréas endocrine. Lorsque la glycémie augmente, notamment après un repas, les cellules bêta pancréatiques libèrent de l’insuline, ce qui favorise l’utilisation et le stockage du glucose et contribue à faire baisser la glycémie. Lorsque la glycémie baisse, les cellules alpha libèrent du glucagon, qui stimule notamment la libération de glucose par le foie. Le foie, le muscle et le tissu adipeux participent aussi à l’homéostasie glucidique.',
    source_files=coalesce(source_files,'[]'::jsonb) || jsonb_build_array(
      jsonb_build_object('label','NIDDK/NIH — Insulin and glucagon in blood glucose regulation','url','https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone','validation','institutional_validated'),
      jsonb_build_object('label','NIDDK/NIH — Pancreas responds to low or high blood glucose levels','url','https://www.niddk.nih.gov/news/media-library/17969','validation','institutional_validated')
    ),
    updated_at=now()
where id='34f967dd-5d5b-47c7-aa48-9acbe746d610'::uuid;

insert into public.curriculum_quiz_questions
(id,topic_id,question_text,explanation,options,difficulty,source_label,display_order,validation_status,is_published,question_type,accepted_answers,image_url,metadata)
values
('d0000001-71a0-4d01-9010-000000000001'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Quel organe assure l’essentiel de l’absorption des nutriments ?','L’intestin grêle absorbe la majeure partie des nutriments issus de la digestion.','[{"text":"L’intestin grêle","correct":true},{"text":"L’œsophage","correct":false},{"text":"Le rectum","correct":false},{"text":"La vésicule biliaire","correct":false}]'::jsonb,1,'NIDDK/NIH — Your Digestive System & How it Works',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000002'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Quel mécanisme fait progresser le contenu dans le tube digestif ?','Le péristaltisme correspond aux contractions coordonnées de la paroi digestive qui font avancer le contenu.','[{"text":"Le péristaltisme","correct":true},{"text":"La filtration glomérulaire","correct":false},{"text":"La ventilation pulmonaire","correct":false},{"text":"La coagulation","correct":false}]'::jsonb,1,'NIDDK/NIH — Your Digestive System & How it Works',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000003'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Quelle est une fonction importante du gros intestin ?','Le gros intestin absorbe notamment de l’eau et participe à la formation des selles.','[{"text":"Absorber de l’eau et former les selles","correct":true},{"text":"Produire l’insuline","correct":false},{"text":"Oxygéner le sang","correct":false},{"text":"Filtrer l’urine","correct":false}]'::jsonb,2,'NIDDK/NIH — Your Digestive System & How it Works',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000004'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Quel organe produit la bile ?','Le foie produit la bile, qui participe notamment à la digestion des graisses.','[{"text":"Le foie","correct":true},{"text":"La vésicule biliaire","correct":false},{"text":"Le côlon","correct":false},{"text":"L’œsophage","correct":false}]'::jsonb,2,'NIDDK/NIH — Your Digestive System & How it Works',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000005'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Quel est le rôle principal de la vésicule biliaire vis-à-vis de la bile ?','La vésicule biliaire stocke la bile produite par le foie et la libère vers l’intestin grêle au moment approprié.','[{"text":"Stocker puis libérer la bile","correct":true},{"text":"Produire l’insuline","correct":false},{"text":"Absorber la majorité des nutriments","correct":false},{"text":"Produire les globules rouges","correct":false}]'::jsonb,2,'NIDDK/NIH — Your Digestive System & How it Works',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000006'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Pourquoi le pancréas est-il considéré comme un organe important de la digestion ?','Le pancréas sécrète dans l’intestin grêle un suc contenant des enzymes qui participent à la digestion des glucides, lipides et protéines.','[{"text":"Il sécrète des enzymes digestives","correct":true},{"text":"Il assure le péristaltisme œsophagien","correct":false},{"text":"Il stocke les selles","correct":false},{"text":"Il fabrique la bile","correct":false}]'::jsonb,3,'NIDDK/NIH — Your Digestive System & How it Works',906,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000007'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Cas d’application — Une altération importante de l’intestin grêle risque surtout d’affecter quelle fonction ?','L’intestin grêle constitue le principal site d’absorption des nutriments digérés.','[{"text":"L’absorption des nutriments","correct":true},{"text":"La production de bile","correct":false},{"text":"La ventilation","correct":false},{"text":"La filtration rénale","correct":false}]'::jsonb,3,'NIDDK/NIH — Your Digestive System & How it Works',907,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000008'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Cas d’application — Un ralentissement marqué du péristaltisme aura d’abord quel effet général ?','Le péristaltisme sert à faire progresser et à mélanger le contenu digestif ; son ralentissement perturbe donc le transit.','[{"text":"Une perturbation de la progression du contenu digestif","correct":true},{"text":"Une augmentation directe de l’oxygénation sanguine","correct":false},{"text":"Une production accrue d’insuline","correct":false},{"text":"Une augmentation de la filtration glomérulaire","correct":false}]'::jsonb,4,'NIDDK/NIH — Your Digestive System & How it Works',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000001-71a0-4d01-9010-000000000009'::uuid,'78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,'Quel ensemble résume le mieux le fonctionnement digestif ?','La digestion associe transport, transformation mécanique et chimique, absorption des nutriments et élimination des résidus.','[{"text":"Transport, digestion, absorption et élimination","correct":true},{"text":"Ventilation, filtration, coagulation et vision","correct":false},{"text":"Contraction cardiaque, audition, sudation et équilibre","correct":false},{"text":"Hématopoïèse, conduction nerveuse, vision et diurèse","correct":false}]'::jsonb,5,'NIDDK/NIH — Your Digestive System & How it Works',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/health-information/digestive-diseases/digestive-system-how-it-works","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000001'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Qu’est-ce qu’une hormone ?','Une hormone est un messager chimique libéré dans l’organisme et capable d’agir sur des cellules ou organes cibles.','[{"text":"Un messager chimique","correct":true},{"text":"Une cellule sanguine","correct":false},{"text":"Une enzyme digestive uniquement","correct":false},{"text":"Un influx électrique uniquement","correct":false}]'::jsonb,1,'MedlinePlus/NIH — Endocrine Diseases',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/endocrinediseases.html","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000002'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Comment une hormone endocrine atteint-elle généralement son organe cible ?','Les hormones endocrines sont libérées dans la circulation sanguine puis transportées vers leurs tissus cibles.','[{"text":"Par la circulation sanguine","correct":true},{"text":"Uniquement par les alvéoles pulmonaires","correct":false},{"text":"Uniquement par les canaux biliaires","correct":false},{"text":"Uniquement par le liquide digestif","correct":false}]'::jsonb,1,'Manuel MSD professionnel — Système endocrinien',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien","minimum_10_batch":"v1","source_validation":"peer_reviewed_reference"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000003'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Pourquoi toutes les cellules ne répondent-elles pas de la même façon à une hormone ?','La réponse dépend notamment de la présence de récepteurs adaptés sur ou dans les cellules cibles.','[{"text":"Parce que les cellules cibles possèdent des récepteurs spécifiques","correct":true},{"text":"Parce que les hormones ne circulent jamais dans le sang","correct":false},{"text":"Parce que toutes les cellules ont exactement la même réponse","correct":false},{"text":"Parce que les hormones agissent uniquement sur les os","correct":false}]'::jsonb,2,'Manuel MSD professionnel — Système endocrinien',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien","minimum_10_batch":"v1","source_validation":"peer_reviewed_reference"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000004'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Le système endocrinien participe notamment à quel ensemble de fonctions ?','Les hormones participent à la croissance, au métabolisme, à la reproduction, à l’humeur et à de nombreux autres processus physiologiques.','[{"text":"Croissance, métabolisme et reproduction","correct":true},{"text":"Uniquement la vision","correct":false},{"text":"Uniquement la coagulation","correct":false},{"text":"Uniquement la digestion mécanique","correct":false}]'::jsonb,2,'MedlinePlus/NIH — Endocrine Diseases',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/endocrinediseases.html","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000005'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Quel type de déséquilibre peut provoquer un trouble endocrinien ?','Une hormone produite en quantité trop faible ou trop importante peut perturber les fonctions régulées par cette hormone.','[{"text":"Une production hormonale trop faible ou trop élevée","correct":true},{"text":"Une absence totale de circulation sanguine locale sans autre conséquence","correct":false},{"text":"Une augmentation du péristaltisme uniquement","correct":false},{"text":"Une variation de la taille des globules rouges uniquement","correct":false}]'::jsonb,2,'MedlinePlus/NIH — Endocrine Diseases',905,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://medlineplus.gov/endocrinediseases.html","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000006'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Cas d’application — Une glande sécrète normalement une hormone, mais le tissu cible y répond mal. Peut-il exister un trouble endocrinien ?','Oui. Un trouble endocrinien peut aussi venir d’une réponse anormale du tissu cible, pas seulement de la quantité d’hormone produite.','[{"text":"Oui, une anomalie de réponse du tissu cible peut suffire","correct":true},{"text":"Non, seul un défaut de production hormonale est possible","correct":false},{"text":"Non, les tissus cibles ne participent jamais aux troubles endocriniens","correct":false},{"text":"Oui, mais uniquement si la digestion est arrêtée","correct":false}]'::jsonb,3,'Manuel MSD professionnel — Système endocrinien',906,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien","minimum_10_batch":"v1","source_validation":"peer_reviewed_reference"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000007'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Quelle propriété distingue une glande endocrine d’une glande exocrine ?','Une glande endocrine libère ses hormones directement dans la circulation plutôt que dans un canal excréteur.','[{"text":"Elle libère ses hormones directement dans la circulation","correct":true},{"text":"Elle déverse toujours son produit dans le tube digestif","correct":false},{"text":"Elle ne produit aucun messager chimique","correct":false},{"text":"Elle agit uniquement par contact mécanique","correct":false}]'::jsonb,3,'Manuel MSD professionnel — Système endocrinien',907,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien","minimum_10_batch":"v1","source_validation":"peer_reviewed_reference"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000008'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Cas d’application — Une hormone circule normalement mais son récepteur est absent sur un tissu. Quelle conséquence est la plus logique ?','Sans récepteur approprié, le tissu ne peut pas répondre normalement au signal hormonal.','[{"text":"Le tissu répondra insuffisamment au signal hormonal","correct":true},{"text":"Le tissu répondra forcément davantage","correct":false},{"text":"L’hormone deviendra une cellule sanguine","correct":false},{"text":"La circulation sanguine s’arrêtera automatiquement","correct":false}]'::jsonb,4,'Manuel MSD professionnel — Système endocrinien',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien","minimum_10_batch":"v1","source_validation":"peer_reviewed_reference"}'::jsonb),
('d0000002-71a0-4d01-9010-000000000009'::uuid,'508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,'Quel raisonnement est le plus juste face à une anomalie endocrinienne ?','Il faut considérer à la fois la glande, la quantité d’hormone produite et la capacité du tissu cible à répondre.','[{"text":"Analyser production hormonale et réponse du tissu cible","correct":true},{"text":"Examiner uniquement la digestion","correct":false},{"text":"Examiner uniquement le nombre de globules rouges","correct":false},{"text":"Conclure toujours à un excès hormonal","correct":false}]'::jsonb,5,'Manuel MSD professionnel — Système endocrinien',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.msdmanuals.com/fr/professional/troubles-endocriniens-et-m%C3%A9taboliques/principes-endocrinologie/revue-g%C3%A9n%C3%A9rale-du-syst%C3%A8me-endocrinien","minimum_10_batch":"v1","source_validation":"peer_reviewed_reference"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000001'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Quelle hormone contribue à faire baisser une glycémie élevée ?','L’insuline est sécrétée par les cellules bêta pancréatiques lorsque la glycémie augmente et favorise son abaissement.','[{"text":"L’insuline","correct":true},{"text":"Le glucagon","correct":false},{"text":"La bile","correct":false},{"text":"L’hémoglobine","correct":false}]'::jsonb,1,'NIDDK/NIH — Régulation de la glycémie',901,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000002'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Quelle hormone contribue à faire remonter une glycémie trop basse ?','Le glucagon est sécrété par les cellules alpha pancréatiques et stimule notamment la libération de glucose par le foie.','[{"text":"Le glucagon","correct":true},{"text":"L’insuline","correct":false},{"text":"La pepsine","correct":false},{"text":"La bilirubine","correct":false}]'::jsonb,1,'NIDDK/NIH — Régulation de la glycémie',902,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000003'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Quelles cellules pancréatiques produisent principalement l’insuline ?','Les cellules bêta des îlots pancréatiques produisent l’insuline.','[{"text":"Les cellules bêta","correct":true},{"text":"Les cellules alpha","correct":false},{"text":"Les hépatocytes","correct":false},{"text":"Les érythrocytes","correct":false}]'::jsonb,2,'NIDDK/NIH — Régulation de la glycémie',903,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000004'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Quelles cellules pancréatiques produisent principalement le glucagon ?','Les cellules alpha des îlots pancréatiques produisent le glucagon.','[{"text":"Les cellules alpha","correct":true},{"text":"Les cellules bêta","correct":false},{"text":"Les adipocytes","correct":false},{"text":"Les plaquettes","correct":false}]'::jsonb,2,'NIDDK/NIH — Régulation de la glycémie',904,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000005'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Après un repas, quelle réponse physiologique est la plus cohérente ?','L’augmentation de la glycémie stimule la sécrétion d’insuline, qui favorise l’entrée et le stockage du glucose.','[{"text":"Augmentation de la sécrétion d’insuline","correct":true},{"text":"Suppression complète de toute hormone pancréatique","correct":false},{"text":"Augmentation systématique du glucagon pour élever encore la glycémie","correct":false},{"text":"Arrêt du stockage hépatique du glucose","correct":false}]'::jsonb,3,'NIDDK/NIH — Régulation de la glycémie',905,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000006'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'En période de jeûne, quelle réponse contribue à maintenir la glycémie ?','Quand la glycémie baisse, le glucagon favorise la libération de glucose par le foie.','[{"text":"Le glucagon stimule la libération hépatique de glucose","correct":true},{"text":"L’insuline augmente fortement pour bloquer la libération hépatique","correct":false},{"text":"Le foie cesse toute participation à la glycémie","correct":false},{"text":"Les globules rouges produisent du glucagon","correct":false}]'::jsonb,3,'NIDDK/NIH — Régulation de la glycémie',906,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000007'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Quel organe joue un rôle central dans le stockage et la libération de glucose sous contrôle hormonal ?','Le foie stocke du glucose après les repas et peut en libérer lorsque la glycémie baisse, notamment sous l’influence du glucagon.','[{"text":"Le foie","correct":true},{"text":"La vésicule biliaire","correct":false},{"text":"La trachée","correct":false},{"text":"Le cristallin","correct":false}]'::jsonb,3,'NIDDK/NIH — Régulation de la glycémie',907,'source_validated',true,'mcq','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000008'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Cas d’application — Une personne sécrète trop peu d’insuline après un repas. Quel effet est le plus attendu ?','Une sécrétion insuffisante d’insuline réduit la capacité à abaisser correctement une glycémie élevée.','[{"text":"La glycémie risque de rester trop élevée","correct":true},{"text":"La glycémie chutera nécessairement à zéro","correct":false},{"text":"Le foie cessera définitivement de fonctionner","correct":false},{"text":"Le glucagon deviendra une enzyme digestive","correct":false}]'::jsonb,4,'NIDDK/NIH — Régulation de la glycémie',908,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb),
('d0000003-71a0-4d01-9010-000000000009'::uuid,'478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid,'Quel énoncé résume le mieux l’homéostasie glycémique ?','L’insuline et le glucagon agissent de façon complémentaire avec plusieurs organes pour maintenir la glycémie dans une plage compatible avec le fonctionnement normal de l’organisme.','[{"text":"Elle repose sur une régulation coordonnée entre hormones et organes","correct":true},{"text":"Elle dépend uniquement de l’intestin","correct":false},{"text":"Elle est indépendante du pancréas","correct":false},{"text":"Elle ne varie jamais avec les repas ou le jeûne","correct":false}]'::jsonb,5,'NIDDK/NIH — Régulation de la glycémie',909,'source_validated',true,'clinical_case','[]'::jsonb,null,'{"source_url":"https://www.niddk.nih.gov/news/archive/2021/story-discovery-medications-diabetes-obesity-emerged-research-pancreatic-hormone","minimum_10_batch":"v1","source_validation":"institutional_validated"}'::jsonb)
on conflict(id) do nothing;

do $
begin
 if exists(
   select 1 from public.curriculum_quiz_readiness_v1
   where topic_id in (
     '78e455b5-75a8-43c8-bd10-22c6e7a27f72'::uuid,
     '508670dc-3dfe-45a4-ac1f-8adee52e88af'::uuid,
     '478c3df1-d7ae-4dfc-a22f-7f737d431a1a'::uuid
   ) and not is_ready
 ) then
   raise exception 'Validated external source batch 1 is not ready: expected >=10 validated questions per topic';
 end if;
end $$;

select public.refresh_release_health_status_v1();
